### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'use' (T_USE)

### ISSUE THREAD

**Issue by DaAwesomeP** [browscap/browscap-php#1]
Hi,
I have used composer for a long time and have been able to avoid using namespaces. This is the first library I have needed to use one. Here is my code:

``` php
use phpbrowscap\Browscap;
$bc = new Browscap($_SERVER["DOCUMENT_ROOT"].'/php/browscap_cache');
$current_browser = $bc->getBrowser();
```

It output's this in the log:

```
PHP Parse error:  syntax error, unexpected 'use' (T_USE)
```

Do I need to put the first line somewhere else? Thanks for any help!

PHP 5.5.1
Apache 2.4.4
Windows 8 x86

**Comment by muthugit** [comment]
I used the use paths outside the class and its work for me
![screen shot 2016-11-05 at 2 07 53 am](https://cloud.githubusercontent.com/assets/12176352/20021620/b1bf4cb0-a2fc-11e6-8a18-d5aec3769097.png)
