### ISSUE TITLE
is the locking mechanism for the cache really working?

### ISSUE THREAD

**Issue by croensch** [browscap/browscap-php#10]
I noticed this library uses a cache file. My experience with file caching in PHP is that simple things like `file_put_contents()` versus `require()` or `file_get_contents()` often fail in multi-core environments. Speaking a multi-core server with Apache in preforking mode.

I've seen it in other libraries for example Zend_Cache_File, breaking our production environment with empty cache files whenever two processes coincidentally collide. That's why i moved everything to php_apc for good.

Now this library does not provide other caching mechanisms, so i'd like to know what measures are taken to keep it running smoothly in a high load multi-core environment.

To demonstrate, run this in the background

``` php
<?php
while (true) {
    $i = rand(1000, 9999);
    file_put_contents('c.php', "<?php echo $i;", LOCK_EX);
}
```

while trying to run this

``` php
<?php require 'c.php';
```

on my CLI i get three results _nothing_, _"Bus error"_ and _a number_.

**Comment by mimmi20** [comment]
@asgrim May we close this issue?

**Comment by asgrim** [comment]
@mimmi20 we already replaced with PSR simple cache, right?

**Comment by mimmi20** [comment]
Yes, in V4.

**Comment by asgrim** [comment]
Ok great, yes this can be closed. Thanks!
