### ISSUE TITLE
Increase performance of browscap 3.x

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-php#101]
As per conversation with @jaydiablo [here](https://github.com/browscap/browscap-php/issues/20#issuecomment-137993153), I'd like to review the performance of the `3.x` series.

Although we have significantly reduced the memory usage in `3.x`, it now takes much longer to process.

@jaydiablo has pinpointed a potential big win:

> This was the biggest win for me when I was trying to optimize crossjoin: https://github.com/crossjoin/Browscap/commit/2ee9663bd4b971c658d87f33fe780858580f7bd4 (the digit replacement in that commit is a bit overzealous, and causes tests to fail, which was fixed later https://github.com/crossjoin/Browscap/commit/afd9f8eaec3fe506ed864a93a536e2370b570922)

Investigate this and see if we can optimise similarly.

**Comment by mimmi20** [comment]
The changes from `crossjoin/Browscap@2ee9663` were reimplemented in the optimize branch and merged at the 26.09.
