### ISSUE TITLE
require PHP 5.3 -> PHP 5.5 in 2.0.5 ?

### ISSUE THREAD

**Issue by nicohofmann** [browscap/browscap-php#103]
Is it possible to change the requirement to PHP 5.3 again for 2.0.x ? I guess it is very hard and bad decision to switch PHP Requirements within a minor version.

**Comment by asgrim** [comment]
To be honest, probably not. Browscap 3 (the master branch, not stable yet) will be min 5.5 at the moment, and we won't be doing any more work on Browscap 2!

**Comment by asgrim** [comment]
(btw, we would not re-release 2.0.5 anyway, it would be in the 2.1.0 release if anything)
