### ISSUE TITLE
Recommended Setup

### ISSUE THREAD

**Issue by georgi-kovachev** [browscap/browscap-php#109]
I have some questions about 'Recommended Setup' in the documentation.
What are these command?
bin/browscap browscap:fetch
bin/browscap browscap:convert

And where is bin folder and I can't find 'browscap' command.
I updated composer.json file and run composer update. 
And it download the browscap-php folder under vendor/browscap.

**Comment by asgrim** [comment]
`vendor/bin/browscap` is the command you're looking for :) I'll update the docs accordingly, thanks

**Comment by georgi-kovachev** [comment]
i am using laravel and i am sure it is nothing to affect the configuration.
After I update composer.json and run 'composer update', I still don't see browscap command under vendor/bin/
I just see phpspec,phpunit,psysh which already exists,
FYI I am using MAMP on mac.

**Comment by georgi-kovachev** [comment]
hi James I can't find the browscap command under vendor/bin.
what can be wrong?

**Comment by asgrim** [comment]
What version did it install? I'm guessing it installed the latest stable (2.0.5), which is a different branch (and thus different instructions): see https://github.com/browscap/browscap-php/tree/2.x

**Comment by georgi-kovachev** [comment]
I followed the instruction of readme file under master branch.
And I noticed it adds "browscap/browscap-php": "~2.0" in componser.json
and inside browscap.php I found this
const VERSION = '2.0.5';
In the readme it says it is new version of 3.0, but it seems like 2.0
Is this 2.0 version?

**Comment by asgrim** [comment]
The README.md on `master` branch is for 3.x: https://github.com/browscap/browscap-php. This is the new alpha version. Note the second paragraph states clearly:

> Note that this is the new version 3 branch now. You can still see the version 2 branch [here](https://github.com/browscap/browscap-php/tree/2.x).

Thanks! :smile:
