### ISSUE TITLE
issues running browscap:fetch

### ISSUE THREAD

**Issue by rorydonohue** [browscap/browscap-php#116]
Hi, 

For the recommended setup in the README, I am having trouble running the following commands:

    vendor/bin/browscap browscap:fetch
    vendor/bin/browscap browscap:convert

I installed the browscap binary from the  "browscap/browscap" repository, however when I run the above commands I get: 

    [InvalidArgumentException]
    There are no commands defined in the "browscap" namespace.

The only available commands seem to be build, diff, grep, help and list. 

And there doesn't appear to be a browscap script in the  "browscap/browscap-php" repository. 

I'm sure I'm missing something super obvious, any help would be greatly appreciated!

**Comment by asgrim** [comment]
@rorydonohue if you installed via composer with default options, you will have the latest stable 2.x version. The instructions you see in the README are for 3.x which is unstable, but is the current master branch.

Your choices are either:

* Use composer to require version [`3.0.0-alpha.1`](https://packagist.org/packages/browscap/browscap-php#3.0.0-alpha.1)
* See the docs for the `2.0.5` or [`2.1.0-alpha.1`](https://github.com/browscap/browscap-php/tree/2.x) versions

**Comment by mimmi20** [comment]
@asgrim the commands @rorydonohue named are included in `browscap/browscap` but not in `browscap/browscap-php`.

**Comment by jerrygrey** [comment]
@asgrim I think that should be spelt out more clearly in the README itself to avoid confusion imo.

**Comment by asgrim** [comment]
@mimmi20 when installing `browscap-php` with composer, the commands will be in `vendor/bin/browscap`, that's what's in the readme as it's the most common usecase.

@jerrygrey good point, I've created PR #117 to resolve this
