### ISSUE TITLE
Due date v3.0.0

### ISSUE THREAD

**Issue by ThaDafinser** [browscap/browscap-php#119]
Hello,

is there already a due date for the v3.0.0?
I currently depend on it here: https://github.com/ThaDafinser/UserAgentParser#minimum-stability-currently

It's okay until i release the v1.0.0, but when i will release v1.0.0 (due date is planned around december) i would like to have only stable providers.

**Comment by asgrim** [comment]
Currently no date is set, it's likely that I'll do the work to convert the website (https://github.com/browscap/browscap-site) to use it first as it's currently using the latest 2.x - as that'll be a fairly good test of functionality (anyone who uses the UA checker).

**Comment by asgrim** [comment]
@ThaDafinser we released beta.1 now, so we're getting there. I expect we'll be in a position to release 3.0.0 by the end of the year

**Comment by asgrim** [comment]
We'll need to do an rc.1 release at least beforehand as the API has changed slightly (see #141)

**Comment by asgrim** [comment]
Almost there for the release. #143 needs to be done so people can take a sensible upgrade path.

I'm really hoping people are using Composer correctly (i.e. using `^2...` instead of `>= 2...`) otherwise they're going to be in for a shock when they update and find everything broken :) so the upgrade docs are pretty important.

**Comment by ThaDafinser** [comment]
> I'm really hoping people are using Composer correctly (i.e. using ^2... instead of >= 2...) 

Dont worry about that. That (should) only happen in development since in production you should only do `composer install` from the lock file.

And if then you dont want the `3.x` just change the `composer.json` and do composer update and you are fine.

**Comment by Sazpaimon** [comment]
Since there's an active PR addressing migration, is there any chance of a release happening any time soon?

**Comment by asgrim** [comment]
Soon - there's 2 PRs left for 3.0.0 release :)

**Comment by ThaDafinser** [comment]
> @ThaDafinser we released beta.1 now, so we're getting there. I expect we'll be in a position to release 3.0.0 by the end of the year

Soon a 3.0 release would be really fine.

**Comment by asgrim** [comment]
@ThaDafinser 3.0.0 is released today: https://github.com/browscap/browscap-php/releases/tag/3.0.0
