### ISSUE TITLE
Different results with get_browser and browscap-php

### ISSUE THREAD

**Issue by wggdeveloper** [browscap/browscap-php#136]
While we have been working on our browscap implementation in LUA I run all the UA strings from [UserAgentString.com](http://www.useragentstring.com/) through `browscap-php` master and the built-in `get_browser` in PHP5.6. The test gave us different results for 109 UAs out of 10770.

The browscap.ini was the full version of the 6011 release.

Please check the [attached file](https://github.com/browscap/browscap-php/files/78620/report.txt) for the test results. The lines marked with `!` are the ones in question.

**Comment by mimmi20** [comment]
@wggdeveloper Could you create a new list with just the Uas in it where you think the detection result of `browscap-php` is wrong?

**Comment by wggdeveloper** [comment]
It is just a matter of grep, but [here](https://github.com/browscap/browscap-php/files/79092/wrong.txt) it is. 

I can not decide which results are actually wrong. My intention with this test was to get a bunch of UA strings and check our implementation if it give the same results as yours. Then I noticed these differences given by a search which strictly follow the ordering of the INI file (e.g. `get_browser`), and a search after some test optimization and possible reordering. If I'm not mistaken, `browscap-php` does some clever substitution to reduce the number of tests, which in result could also affect the order of the tests.

**Comment by mimmi20** [comment]
@asgrim Could you move this issue to browscap/browscap? I dont think we can solve it here.
