### ISSUE TITLE
3.x Change resources directory path

### ISSUE THREAD

**Issue by BassemN** [browscap/browscap-php#140]
Hi,
Great plugin!!
How can I change build directory path to be outside the vendor directory(Installed via composer) to make sure that build directory didn't removed after updating browscap-php via composer?
Also can this plugin run on PHP 5.3?

Thanks

**Comment by mimmi20** [comment]
@BassemN You need PHP 5.5.

**Comment by BassemN** [comment]
@mimmi20 Ok Thanks and what about changing  build directory path?

**Comment by mimmi20** [comment]
@BassemN What do you want to do that you need the build directory?

**Comment by mimmi20** [comment]
@BassemN Where did you find the build directory? This library did not have one?

**Comment by BassemN** [comment]
@mimmi20 After runing this command `vendor/bin/browscap-php browscap:update` I notice the creations of `resources` directory within the vendor directory. I need to change that path.

**Comment by mimmi20** [comment]
@BassemN At the moment this is not possible. I will add an option

**Comment by BassemN** [comment]
@mimmi20 Thank you very much. Hope to see this option soon :)
