### ISSUE TITLE
A bit wired (at least in my head)

### ISSUE THREAD

**Issue by ThaDafinser** [browscap/browscap-php#150]
It's possible to start a browcap instance with following different initial parameters/dependencies
- with a file loader + cache (per default file)
  - with no warm cache
  - with a warm cache
- only with a cache (should be warm)

When calling `convertFile()` the cache is warmed up.

My problem is now the case, when there is no (warm) cache.
Until yet i thought, when i use `getBrowser()` the cache would be automatically created - but that seems not be that way.

That use case just come up, when i wrote some integration tests for the new splitted for each abstraction here:
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/AbstractBrowscap.php#L63

The type can be null/blank since the cache is not required.

Where shall we put the data file type check?
The problem is, that only the "warm cache" or only the file loader can exist (but not both are required)

Any idea?

**Comment by mimmi20** [comment]
Because of the time which is required to create the cache, it was decided to split that function apart in version 3. Actually Browscap (V3) does only work with a warm cache.

**Comment by asgrim** [comment]
Yes, this automatic creation of the cache is a pain point for supporting, and we have to recommend all the time that people run cache update in the background due to memory usage etc. - hopefully this is less of an issue in V3, but I think separation of these is important.

Therefore, we should encourage warming cache beforehand, rather than "magically" on the fly.

**Comment by ThaDafinser** [comment]
> Actually Browscap (V3) does only work with a warm cache.

I just wrote a integration test  to test this behaivour. 
It seems that it ***works without a warm cache***

Or did i missunderstood something?

The test if the cache is warm
https://github.com/ThaDafinser/UserAgentParser/blob/feature/intergration-test/src/Provider/AbstractBrowscap.php#L63-L65

The intergration tests, which fail because the cache is not set
https://github.com/ThaDafinser/UserAgentParser/blob/feature/intergration-test/tests/integration/Provider/BrowscapLiteTest.php#L58-L85

see PR with build https://github.com/ThaDafinser/UserAgentParser/pull/72

**Comment by ThaDafinser** [comment]
There is also this small test, to verify that browscap returned something, without a cache https://github.com/ThaDafinser/UserAgentParser/blob/feature/intergration-test/tests/integration/Provider/BrowscapLiteTest.php#L79-L80

**Comment by mimmi20** [comment]
It may work without a warm Cache, but you should get always `Default Browser` as result, because this is a fallback, if nothing matches.

**Comment by ThaDafinser** [comment]
> It may work without a warm Cache, but you should get always Default Browser as result, because this is a fallback, if nothing matches.

@mimmi20 you are right, just a Default browser is returned, but isn't that a problem?
As a end user i would think there is no matching result instead of a missing cache?
Require a valid/warm cache would be better in this case, or do i miss something

https://github.com/ThaDafinser/UserAgentParser/blob/feature/intergration-test/tests/integration/Provider/BrowscapLiteTest.php#L33-L52

**Comment by mimmi20** [comment]
@ThaDafinser Would you like it, that we throw an exception, if the cache is not available or warmed up?

**Comment by ThaDafinser** [comment]
If the warm cache is required that it works, then it's a dependency which needs to be somehow checked IMO. Be it an exception or something else doesnt matter.

Dunno what's the best thing at the current state. If i would have an empty project i would proabably completely split the cache warm-up and file conversion from the rest completely.

**Comment by asgrim** [comment]
If a warm cache is required (as is my assumption) then yes, we should throw an exception if the cache is not found.
