### ISSUE TITLE
platform version not fetch

### ISSUE THREAD

**Issue by alexliIgnite** [browscap/browscap-php#153]
Hi, I just install project in php5.6 in ubuntu server, 
everything looks fine to me, it working, but when I look through the useragent like this one
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

it dose not give me platform version and a lot of other results from pharser looks different from the one I check on project website, 
here is what I got from the tool, you can see there is a lot of unknowns that did available when I check with tools you have in your website. 
 
object(stdClass)#13 (50) { ["browser_name_regex"]=> string(105) "/^mozilla\/5\.0 \(.*windows nt 10\.0.*\) applewebkit\/.* \(khtml, like gecko\) chrome\/49\..*safari\/.*$/" ["browser_name_pattern"]=> string(85) "mozilla/5.0 (*windows nt 10.0*) applewebkit/* (khtml, like gecko) chrome/49.*safari/*" ["parent"]=> string(11) "Chrome 49.0" ["comment"]=> string(11) "Chrome 49.0" ["browser"]=> string(6) "Chrome" ["browser_type"]=> string(7) "unknown" ["browser_bits"]=> string(1) "0" ["browser_maker"]=> string(10) "Google Inc" ["browser_modus"]=> string(7) "unknown" ["version"]=> string(4) "49.0" ["majorver"]=> string(2) "49" ["minorver"]=> string(1) "0" ["platform"]=> string(5) "Win10" ["platform_version"]=> string(7) "unknown" ["platform_description"]=> string(7) "unknown" ["platform_bits"]=> string(1) "0" ["platform_maker"]=> string(7) "unknown" ["alpha"]=> string(5) "false" ["beta"]=> string(5) "false" ["win16"]=> string(5) "false" ["win32"]=> string(5) "false" ["win64"]=> string(5) "false" ["frames"]=> string(5) "false" ["iframes"]=> string(5) "false" ["tables"]=> string(5) "false" ["cookies"]=> string(5) "false" ["backgroundsounds"]=> string(5) "false" ["javascript"]=> string(5) "false" ["vbscript"]=> string(5) "false" ["javaapplets"]=> string(5) "false" ["activexcontrols"]=> string(5) "false" ["ismobiledevice"]=> bool(false) ["istablet"]=> bool(false) ["issyndicationreader"]=> string(5) "false" ["crawler"]=> bool(false) ["isfake"]=> string(5) "false" ["isanonymized"]=> string(5) "false" ["ismodified"]=> string(5) "false" ["cssversion"]=> string(1) "0" ["aolversion"]=> string(1) "0" ["device_name"]=> string(7) "unknown" ["device_maker"]=> string(7) "unknown" ["device_type"]=> string(7) "Desktop" ["device_pointing_method"]=> string(5) "mouse" ["device_code_name"]=> string(7) "unknown" ["device_brand_name"]=> string(7) "unknown" ["renderingengine_name"]=> string(7) "unknown" ["renderingengine_version"]=> string(7) "unknown" ["renderingengine_description"]=> string(7) "unknown" ["renderingengine_maker"]=> string(7) "unknown" }

**Comment by mimmi20** [comment]
Which browscap file did you use?

**Comment by alexliIgnite** [comment]
vendor/bin/browscap-php browscap:fetch
vendor/bin/browscap-php browscap:convert

I ran these two command, one thing I noticed that my bin folder is not under vendor, I did have bin folder under vendor, but dose not contain browscap-php,

**Comment by asgrim** [comment]
@alexliIgnite which version are you using? 2.x or 3.x?

**Comment by alexliIgnite** [comment]
3.x on master

**Comment by mimmi20** [comment]
@alexliIgnite With the commands you used you use the `standard` file. The properties you mentioned are not in that file, but they are part of the output. (Maybe we should change that.)

If you want these properties, please use the `-r` parameter.

vendor/bin/browscap-php browscap:fetch -r Full_PHP_BrowscapINI

**Comment by alexliIgnite** [comment]
when I run this command 
I got
 there is no cached version available, please update from remote 

but it works

thank you
