### ISSUE TITLE
Formatter for BC with 2.x

### ISSUE THREAD

**Issue by Sazpaimon** [browscap/browscap-php#158]
I think it'd be useful if there were a formatter that works similar to how 2.x worked. For instance, in 2.x, properties would only be shown if they were in the ini that you requested, so properties from full wouldn't show if you requested the default ini. Also, in 2.x, property names were only in lowercase when  specified.

I can make a PR if such a thing would be accepted

**Comment by mimmi20** [comment]
There is nothing to say against this.
