### ISSUE TITLE
daunting migration from v2 to v3

### ISSUE THREAD

**Issue by neokio** [browscap/browscap-php#162]
I'm a huge fan of the simplicity and awesomeness of Browscap v2! Drag browscap.php wherever you want, add a cache dir with the right permissions, run it once with 3 lines of code, and BAM. Done. Efficient and clean.

For users like me, who don't use Composer/Symphony, and who prefer not to fill their codebase with hundreds of unknown files that serve no clear purpose, version 3.0.0rc1 is incomprehensible and seemingly unusable. If there IS away to use it without Composer, the method is not described on github or browscap.org, and I'd very much suggest writing up a quick, basic install walkthrough.

My question I suppose is, for what conceivable purpose has Browscap become so complicated? What does v3 do that v2 doesn't, and is it worth alienating what is likely a significant percentage of your userbase?

**Comment by asgrim** [comment]
Sorry, we won't be supporting installation without Composer with v3 on.

Also, upgrading to 3 is totally optional, use what works for you :) version
3 improves on significant memory usage issues we see with version 2, as
well as taking a bit of a stronger stance with better workflow (i.e.
removing auto update and forcing a back end system to trigger updates
etc.), and making it more extensible.

Browscap.org doesn't have information on how to install & use libraries
anyway, so we wouldn't add that anyway.

Hope this helps!

**Comment by neokio** [comment]
Well, maybe it's time I get my Composer on.
I'd love to know the performance benefits of v3 over v2.
On my local system (with Browscap v2), 1 lookup takes 300ms, and 10 lookups take 650ms total.
Do you have any comparison stats you can share?

**Comment by asgrim** [comment]
It's primarily memory problems we see on smaller systems - see #20 for a long thread on memory issues. We've tried a lot to organise the INI files so that the "normal" file is not too oversized. There are some comparison stats for an early version of 3 over 2 here: https://github.com/browscap/browscap-php/issues/20#issuecomment-137993153

Composer is great! :)

**Comment by asgrim** [comment]
FYI there is a migration guide we're working on in the README.md - you can see the WIP and give feedback onto #154, would be very appreciated!
