### ISSUE TITLE
cURL error 28: Operation timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by sergey-rud** [browscap/browscap-php#172]
Hi!

I have successfully run `vendor/bin/browscap-php browscap:fetch`

But when I execute `vendor/bin/browscap-php browscap:fetch --remote-file "Full_PHP_BrowscapINI"` I get an error:

>  [GuzzleHttp\Exception\ConnectException]  
>   cURL error 28: Operation timed out after 5000 milliseconds with 16084023 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

How can I fix that?

Thank you.

**Comment by asgrim** [comment]
@sergey-rud we're working on this to provide an API to update the timeout (and increase default). For now please see #166 for suggested fix. HTH!

**Comment by sergey-rud** [comment]
Thank you for a quick answer. I hope you will release a patch with that fix soon.

Best regards.

**Comment by solicomo** [comment]
Is there any update on this issue? 

It seems that #166 dose not provide an API to set the private $timeout for users.

**Comment by asgrim** [comment]
This is not released yet. There was a PR made in #171 but it doesn't look like the author has updated it yet.

**Comment by psytraxx** [comment]
its the line 

$response = $this->getClient()->get($uri, ['timeout' => 5]);

src/BrowscapUpdater.php

can one not just remove that option - default is 0 - no timeout which would fix this issue too

**Comment by asgrim** [comment]
Already fixed in #175. Not released yet though; will be in next release (probably `3.1.0`)
