### ISSUE TITLE
replace WurflCache with doctrine/cache

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap-php#174]
I dont want to support the WurflCache package any longer. For this the package should be replaced with the PSR-6 compliant [php-cache package](https://github.com/php-cache/cache).

**Comment by asgrim** [comment]
PSR-6 was a bit of a failure by many accounts, and I believe a new caching standard has recently been accepted ([PSR-16](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-16-simple-cache.md)) that resolves the issues with PSR-6.

**Comment by mimmi20** [comment]
Then I would use [scrapbook] (https://github.com/matthiasmullie/scrapbook).

**Comment by asgrim** [comment]
I'd suggest we use `doctrine/cache` really; it's a MUCH more widely used cache. Only downside is no PSR-16 support, but I'm [working on that](Roave/DoctrineSimpleCache#1) as we speak

**Comment by mimmi20** [comment]
Could you post a coment here, if that package is ready for use?

**Comment by asgrim** [comment]
yup, 'course

**Comment by mimmi20** [comment]
I dont think your package is usable here, because it doesn't support PHP versions below 7.1.

**Comment by asgrim** [comment]
We can always bump minimum version to 7.1 ;)
