### ISSUE TITLE
Tablet detected as Smartphone

### ISSUE THREAD

**Issue by Froxz** [browscap/browscap-php#178]
Hi,
Samsung Tablet Tab S is detected as mobile not tablet, is there is workaround on this?

**Comment by mimmi20** [comment]
Please open a ticket in the browscap/browscap project and add the useragent of the device.

**Comment by asgrim** [comment]
@Froxz yes, please open a ticket in https://github.com/browscap/browscap/issues/new - make sure you include at least one sample UA string, thanks!
