### ISSUE TITLE
No Active Cache Available

### ISSUE THREAD

**Issue by WhiteLoti** [browscap/browscap-php#188]
I followed all the steps for setting browscap and caching the Full_PHP_BrowscapINI but I'm still getting the error "Uncaught exception 'BrowscapPHP\Excption' with message 'there s no active cache available, please run the update command' in composer/vendor/browscap/browscap-php/src/Browscap.php. I checked and that file doesn't have a function for update the BrowscapUpdater.php file does. I ran the command on both but files just to be sure. I got the errors:

    .Browscap.php: line 1: ?php: No such file or directory
    .Browscap.php: line 2: /bin: is a directory
    .Browscap.php: line 3: syntax error near  unexpected token `('
    .Browscap.php: line 3: ` * Copyright (c) 1998-2015 Browser Compatibilities Project'

I got the same with BrowscapUpdater.php. 

The steps I followed were:
1. Recommended Setup part a.
2. Setting up a Memcached
3. Taking the user agent from the global $_SERVER variable 

Can anyone tell me what I might have done wrong?

**Comment by mimmi20** [comment]
Please add the code you are using to call Browscap and some information like PHP version, OS.

**Comment by WhiteLoti** [comment]
Ubuntu 12.04.5 LTS x86_x64
PHP v5.6.29

CLI
    cd composer/vendor/bin 
    ./browscap-php browscap:fetch –r Full_PHP_BrowscapINI ./browscap-cache
    ./browscap-php browscap:convert

PHP_SCRIPT
    $memcached_configs = array('host'=>'127.0.0.1','port'=>'11211','namespace'=>'wurfl','cacheExpiration'=>0);
    $wurfl_cache = new \WurflCache\Adapter\Memcached($memcached_configs);
    $browscap = new \BrowscapPHP\Browscap();
    $browscap->setCache($wurfl_cache);
    print_r($browscap->getBrowser());

**Comment by mimmi20** [comment]
This is an error in the documentation. If you are using Memcache, you can't use the CLI scripts.

**Comment by WhiteLoti** [comment]
This may be out of your scope but how do I get the wurfl adapter to work with the cached file in memcached. 

How can I use the setCache function in BrowscapUpdater if it isn't returned to an object such as browscap?

**Comment by mimmi20** [comment]
You have to set the same cache object to the BrowscapUpdater as you set to Browscap.

**Comment by WhiteLoti** [comment]
Here is my code so far and I'm still getting the same error.
`    $memcached_configs = array('host'=>'127.0.0.1','port'=>'11211','namespace'=>'wurfl','cacheExpiration'=>0)
     $wurfl_cache = new \WurflCache\Adapter\Memcached($memcached_configs);
     $browscap_updater = new \BrowscapPHP\BrowscapUpdater();
     $browscap_updater->setCache($wurfl_cache);
     $browscap = new \BrowscapPHP\Browscap();
     $browscap->setCache($browscap_updater->getCache());
`

and I'm still getting the error "'BrowscapPHP\Exception' with message 'there is no active cache available, please run the update command.'" Would this error be caused by my memcached do not wanting to start maybe?

**Comment by asgrim** [comment]
@WhiteLoti please can you provide a full stack trace, helps debugging - thanks!

**Comment by mimmi20** [comment]
@WhiteLoti Please add `$browscap_updater->update(\BrowscapPHP\Helper\IniLoader::PHP_INI_FULL);` after the 4. line.
Please use `$browscap->setCache($wurfl_cache);`.

**Comment by mimmi20** [comment]
@WhiteLoti Please split this script into two scripts, one for the update and one for the detecting.

**Comment by WhiteLoti** [comment]
These are the two script I have. Is this what you meant @mimmi20?

$browscap_updater = new \BrowscapPHP\BrowscapUpdater();
$browscap_updater->update(\BrowscapPHP\Helper\IniLoader::PHP_INI_FULL);

$memcached_configs = array('host'=>'127.0.0.1','port'=>'11211','namespace'=>'wurfl','cacheExpiration'=>0);
$wurfl_cache = new \WurflCache\Adapter\Memcached($memcached_configs);
$browscap = new \BrowscapPHP\Browscap();
$browscap->setCache($wurfl_cache);

Here is the error I'm getting.

Uncaught exception 'BrowscapPHP\Exception' with message 'there is no active cache available, please run the update command' in composer/vendor/browscap/browscap-php/src/Browscap.php:231

Should I check that memcached is even running?

**Comment by mimmi20** [comment]
Your memchached has to run, to get this working.

**Comment by WhiteLoti** [comment]
I have tried everything I can think of to get memcached to work including looking at several websites for installation and configuration.  I can start memcached but when I go to check the status it says not running. I am thinking of switching caching. Would wurfl-cache work with Redis?

**Comment by WhiteLoti** [comment]
I'm running it on a Ubuntu 12.04 LTS machine with php v5.6. Is memcache different from memcached? Is memcached not support in php v5.6?

I'm still getting the error:  Uncaught exception 'WurflCache\Adapter\Exception' with message 'The PHP extension memcached must be installed and loaded in order to use the Memcached

I keep seeing how to setup memcache on apache but I didn't see anything about memcached.

**Comment by asgrim** [comment]
This isn't a support forum for memcached. Once you have memcached working, we can help you with the browscap library.
