### ISSUE TITLE
Extracting properties

### ISSUE THREAD

**Issue by simontong** [browscap/browscap-php#189]
Whats the best way of going about extracting properties without having to provide user_agents?
eg a list of Device_Types:
Tablet
iPhone
etc.
etc.

**Comment by mimmi20** [comment]
Please look into the file  src/Data/PropertyHolder.php into the function `checkValueInArray`. You will find all possible values in there. This function validates the values from the ini file.

**Comment by simontong** [comment]
Ah yes. My mistake!
