### ISSUE TITLE
Guzzle times out when downloading any browscap file

### ISSUE THREAD

**Issue by WhiteLoti** [browscap/browscap-php#190]
```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 5000 milliseconds with 2225643 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /www/composer/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /www/composer/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /www/composer/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /www/composer/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /www/composer/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /www/composer/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /www/composer/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(42): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /www/composer/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /www/composer/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /www/composer/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /www/composer/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /www/composer/vendor/guzzlehttp/guzzle/src/Client.php(275): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /www/composer/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /www/composer/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /www/composer/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('get', 'http://browscap...', Array)
#14 /www/composer/vendor/browscap/browscap-php/src/BrowscapUpdater.php(289): GuzzleHttp\Client->__call('get', Array)
#15 /www/BrowscapUpdater.php(38): BrowscapPHP\BrowscapUpdater->update('Full_PHP_Browsc...')
#16 /www/BrowscapUpdater.php(50): BrowscapUpdater->__construct()
```

Any suggestions?

Here's the script
```
class BrowscapUpdater
 13 {
 14     public $datetime;
 15 
 16     public function __construct()
 17     {
 18         $this->datetime = new DateTime('now',new DateTimeZone('America/Indiana/Indianapolis'));
 19 
 20         try
 21         {
 22             require_once(__DIR__.'/composer/vendor/autoload.php');
 23         }
 24         catch(Exception $e)
 25         {
 26             error_log("Composer failed to load at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/BrowscapUpdater_log');
 27         }
 28 
 29         try
 30         {
 31             $memcached_configs = array('host'=>'127.0.0.1',
 32                                        'port'=>11211,
 33                                   'namespace'=>'wurfl',
 34                             'cacheExpiration'=>0);
 35             $wurfl_cache = new \WurflCache\Adapter\Memcached($memcached_configs);
 36             $browscap_updater = new \BrowscapPHP\BrowscapUpdater();
 37             $browscap_updater->setCache($wurfl_cache);
 38             $browscap_updater->update(\BrowscapPHP\Helper\IniLoader::PHP_INI_FULL);
 39             $file_handle = fopen('logs/v0/BrowscapUpdater_log','w');
 40             fwrite($file_handle, "Browscap cache successfully updated at {$this->datetime->format('Y/m/d H:i:s\zP')}\n");
 41         }
 42         catch(Exception $e)
 43         {
 44             echo $e;
 45             error_log("Browscap failed to update cache at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/BrowscapUpdater_log');
 46         }
 47     }
 48 }
 49 
 50$update = new BrowscapUpdater();
```

**Comment by mimmi20** [comment]
Did you try to ping the browscap.org domain? You can also set an timeout with `setConnectTimeout($connectTimeout)`.

**Comment by WhiteLoti** [comment]
The ping to browscap.org is working fine. Where do I look for the setconnectTimeout($connectTimeout)? I didn't find it in the CurlFactory.php

**Comment by WhiteLoti** [comment]
Is new  new BrowscapUpdater not namespaced to new \BrowscapPHP\BrowscapUpdater()?

The $connectTimout is in milliseconds right?

Anyway here's what I updated in BrowscapUpdater.php 

$memcached_configs = array('host'=>'127.0.0.1',
 34                                        'port'=>11211,
 35                                   'namespace'=>'wurfl',
 36                             'cacheExpiration'=>0);
 37             $wurfl_cache = new \WurflCache\Adapter\Memcached($memcached_configs);
 38             #$browscap_updater = new \BrowscapPHP\BrowscapUpdater();
 39             $browscap_updater = new BrowscapUpdater();
 40             $browscap_updater->setCache($wurfl_cache);
 41             $browscap_updater->setConnectTimeout(10000);
 42             $browscap_updater->update(\BrowscapPHP\Helper\IniLoader::PHP_INI_FULL);

Getting a new error now. 

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in /www/composer/vendor/mimmi20/wurflcache/src/Adapter/Memcached.php on line 242

I tried increasing the memory limit with ini_set('memory_limit','1024M'); and still got the same error

**Comment by mimmi20** [comment]
@WhiteLoti Then use more memory.

**Comment by WhiteLoti** [comment]
@mimmi20 Is setConnectTime in milliseconds or seconds?

**Comment by mimmi20** [comment]
It should be seconds.

**Comment by WhiteLoti** [comment]
Why is no one else having trouble with this? I changed the memory limit in both my BrowscapUpdater.php and AbstractAdapter.php along with my Memcached instance to 2GB, why am I still having this problem?

PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in /www/composer/vendor/mimmi20/wurflcache/src/Adapter/AbstractAdapter.php on line 257

**Comment by WhiteLoti** [comment]
Why am I getting no active cache? 

Fatal error: Uncaught BrowscapPHP\Exception: there is no active cache available, please run the update command in /www/composer/vendor/browscap/browscap-php/src/Browscap.php

I used the browscap vendor/bin/browscap-php browscap:update --remote-file Full_PHP_BrowscapINI

**Comment by mimmi20** [comment]
If you use the CLI command you can't use Memcache.

**Comment by WhiteLoti** [comment]
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in /www/composer/vendor/mimmi20/wurflcache/src/Adapter/AbstractAdapter.php on line 257
I still keep getting this error. I increased the memory on the AbstractAdapter.php script, BrowscapUpdater.php script and memcache to 2G. Where am I messing up?

`18     public function __construct()
     19     {
     20         $this->datetime = new DateTime('now',new DateTimeZone('America/Indiana/Indianapolis'));
     21 
     22         try
     23         {
     24             require_once(__DIR__.'/composer/vendor/autoload.php');
     25         }
     26         catch(Exception $e)
     27         {
     28             error_log("Composer failed to load at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/BrowscapUpdater_log');
     29         }
     30 
     31         try
     32         {
     33             $memcached_configs = array('host'=>'127.0.0.1',
     34                                        'port'=>11211,
     35                                   'namespace'=>'wurfl',
     36                             'cacheExpiration'=>0);
     37             $wurfl_cache = new \WurflCache\Adapter\Memcached($memcached_configs);
     38             #$browscap_updater = new \BrowscapPHP\BrowscapUpdater();
     39             $browscap_updater = new BrowscapUpdater();
     40             $browscap_updater->setCache($wurfl_cache);
     41             $browscap_updater->setConnectTimeout(120);
     42             $browscap_updater->update(\BrowscapPHP\Helper\IniLoader::PHP_INI_FULL);
     43             $file_handle = fopen('logs/v0/BrowscapUpdater_log','w');
     44             fwrite($file_handle, "Browscap cache successfully updated at {$this->datetime->format('Y/m/d H:i:s\zP')}\n");
     45             fclose($file_handle);
     46         }
     47         catch(Exception $e)
     48         {
     49             echo $e;
     50             error_log("Browscap failed to update cache at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/BrowscapUpdater_log');
     51         }
     52    }
`

**Comment by WhiteLoti** [comment]
PHP Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in /www/composer/vendor/mimmi20/wurflcache/src/Adapter/AbstractAdapter.php on line 257
I still keep getting this error. I increased the memory on the AbstractAdapter.php script, BrowscapUpdater.php script and memcache to 2G. Where am I messing up?

     14 class BrowscapUpdater
     15 {
     16     public $datetime;
     17 
     18     public function __construct()
     19     {
     20         $this->datetime = new DateTime('now',new DateTimeZone('America/Indiana/Indianapolis'));
     21 
     22         try
     23         {
     24             require_once(__DIR__.'/composer/vendor/autoload.php');
     25         }
     26         catch(Exception $e)
     27         {
     28             error_log("Composer failed to load at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/BrowscapUpdater_log');
     29         }
     30 
     31         try
     32         {
     33             $memcached_configs = array('host'=>'127.0.0.1',
     34                                        'port'=>11211,
     35                                   'namespace'=>'wurfl',
     36                             'cacheExpiration'=>0);
     37             $wurfl_cache = new \WurflCache\Adapter\Memcached($memcached_configs);
     38             $browscap_updater = new \BrowscapPHP\BrowscapUpdater();
     39             $browscap_updater->setCache($wurfl_cache);
     40             $browscap_updater->setConnectTimeout(120);
     41             $browscap_updater->update(\BrowscapPHP\Helper\IniLoader::PHP_INI_FULL);
     42             $file_handle = fopen('logs/v0/BrowscapUpdater_log','w');
     43             fwrite($file_handle, "Browscap cache successfully updated at {$this->datetime->format('Y/m/d H:i:s\zP')}\n");
     44             fclose($file_handle);
     45         }
     46         catch(Exception $e)
     47         {
     48             echo $e;
     49             error_log("Browscap failed to update cache at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/BrowscapUpdater_log');
     50         }
     51     }
     52 }

**Comment by mimmi20** [comment]
Could you try your script with a file cache?

**Comment by WhiteLoti** [comment]
How so?

**Comment by mimmi20** [comment]
$wurfl_cache = new \WurflCache\Adapter\File(array('DIR' => '<dir>'));

**Comment by WhiteLoti** [comment]
The cached was downloaded, however the cache it s not appearing for Browscap.

Fatal error: Uncaught BrowscapPHP\Exception: there is no active cache available, please run the update command in /www/composer/vendor/browscap/browscap-php/src/Browscap.php:231 Stack trace: #0 /www/PageLoader.php(58): BrowscapPHP\Browscap->getBrowser() #1 /www/public/index.php(14): PageLoader->__construct() #2 {main} thrown in /www/composer/vendor/browscap/browscap-php/src/Browscap.php on line 231

 55         $browscap = new \BrowscapPHP\Browscap();
 56         $adapter = new \WurflCache\Adapter\File([\WurflCache\Adapter\File::DIR => 'composer/cache']);
 57         $browscap->setCache($adapter);
 58         print_r($browscap->getBrowser());

**Comment by mimmi20** [comment]
Did you set the same cache to the updater?

**Comment by WhiteLoti** [comment]
This is from my BrowscapUpdater.php Script

```
 33             $wurfl_cache = new \WurflCache\Adapter\File(array('DIR' => __DIR__.'/composer/cache'));
 34             $browscap_updater = new \BrowscapPHP\BrowscapUpdater();
 35             $browscap_updater->setCache($wurfl_cache);
 36             $browscap_updater->setConnectTimeout(60);
 37             $browscap_updater->update(\BrowscapPHP\Helper\IniLoader::PHP_INI_FULL);
 38             $file_handle = fopen('logs/v0/BrowscapUpdater_log','w');
 39             fwrite($file_handle, "Browscap cache successfully updated at {$this->datetime->format('Y/m/d H:i:s\zP')}\n");
 40             fclose($file_handle);
```


This is from my Browscap.php Script

```
 55         $browscap = new \BrowscapPHP\Browscap();
 56         $adapter = new \WurflCache\Adapter\File([\WurflCache\Adapter\File::DIR => __DIR__.'/composer/cache']);
 57         $browscap->setCache($adapter);
 58         print_r($browscap->getBrowser());
```

**Comment by mimmi20** [comment]
Cozuld you post your complste scripts? I dont really understand what you are doing.

**Comment by WhiteLoti** [comment]
This is the update php script
 ```
12 ini_set('memory_limit','3072');
 13 
 14 class BrowscapUpdater
 15 {
 16     public $datetime;
 17  
18     public function __construct()
 19     {
 20         $this->datetime = new DateTime('now',new DateTimeZone('America/Indiana/Indianapolis'));
 21 
 22         try
 23         {
 24             require_once(__DIR__.'/composer/vendor/autoload.php');
 25         }
 26         catch(Exception $e)
 27         {
 28             error_log("Composer failed to load at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/BrowscapUpdater_log');
 29         }
 30 
 31         try
 32         {
 33             $wurfl_cache = new \WurflCache\Adapter\File(array('DIR' => __DIR__.'/composer/cache'));
 34             $browscap_updater = new \BrowscapPHP\BrowscapUpdater();
 35             $browscap_updater->setCache($wurfl_cache);
 36             $browscap_updater->setConnectTimeout(60);
 37             $browscap_updater->update(\BrowscapPHP\Helper\IniLoader::PHP_INI_FULL);
 38             $file_handle = fopen('logs/v0/BrowscapUpdater_log','w');
 39             fwrite($file_handle, "Browscap cache successfully updated at {$this->datetime->format('Y/m/d H:i:s\zP')}\n");
 40             fclose($file_handle);
 41         }
 42         catch(Exception $e)
 43         {
 44             echo $e;
 45             error_log("Browscap failed to update cache at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/BrowscapUpdater_log');
 46         }
 47     }
 48 }
 49 
 50 $update = new BrowscapUpdater();
```

This is the browscap script.I changed the adapter to file cache as suggested. All I'm trying to do is load browscap from cache, not disk because that is too slow. Display the browscap for the given user agent string. Pretty simple.
 ```
19 class PageLoader
 20 {
 21 
 22     public $datetime;
 23 
 24     private $browscap;
 25 
 26 
 27     public function __construct()
 28     {
 29 
 30         $this->datetime = new DateTime('now',new DateTimeZone('America/Indiana/Indianapolis'));
 31 
 32         try
 33         {
 34             require_once(__DIR__.'/composer/vendor/autoload.php');
 35         }
 36         catch(Exception $e)
 37         {
 38             error_log("Composer failed to load at {$this->datetime->format('Y/m/d H:i:s\zP')}\n",3,__DIR__.'/logs/v0/PageLoader_log');
 39         }
 40 
 41         $browscap = new \BrowscapPHP\Browscap();
 42         $adapter = new \WurflCache\Adapter\File([\WurflCache\Adapter\File::DIR => __DIR__.'/composer/cache']);
 43         $browscap->setCache($adapter);
 44         print_r($browscap->getBrowser());
 45     }
 46 }
```
