### ISSUE TITLE
Create a separate component for Apache logfile reader

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-php#191]
I want to try to keep the focus of `browscap-php` on only updating/parsing the INI. Therefore, want to look at removing the Apache logfile reader and creating a separate library for doing this task.

**Comment by Slamdunk** [comment]
This is a good intention, but if you don't have time for it now, can this be postponed in `4.1` or `5.0`, so we can have the `4.0` release with Symfony 4.0 support?

**Comment by Slamdunk** [comment]
Ping @asgrim

**Comment by asgrim** [comment]
Symfony 4 is already supported in `master`, just use that for now, we'll do a release soon I'm sure

**Comment by asgrim** [comment]
Fixed with #232
