### ISSUE TITLE
Add type declarations throughout, including ` : void` (php 7.1)

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-php#194]
Bump version to PHP 7.1 and add type declarations for parameters and return values throughout the project, including ` : void`.

**Comment by asgrim** [comment]
This is in progress at the moment.

**Comment by mimmi20** [comment]
Which IDE are you using? My IDE (version) doesn't support PHP 7.x features.

**Comment by asgrim** [comment]
PhpStorm :)
