### ISSUE TITLE
Browscap::setCache accepts mixed types

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-php#198]
We should enforce only one cache type (`BrowscapCacheInterface`) rather than allowing different types, leave it up to type system to complain about incompatible types, but provide a way to factory those easily , e.g. in #192

**Comment by asgrim** [comment]
Also applies to `BrowscapUpdater::setCache`

**Comment by mimmi20** [comment]
This relates also to #174.

**Comment by asgrim** [comment]
Yep
