### ISSUE TITLE
Not getting user agent string array

### ISSUE THREAD

**Issue by WhiteLoti** [browscap/browscap-php#204]
I have the browscap.ini full version cache and I think all of it is working except retrieving the user_agent_string server variable. Nothing appears in the array, not even the browser_name_regex

My User Agent String is Mozilla/5.0 (X11: Linux x85_64: rev52.0) Gecko/20100101 Firefox/52.0
My browscap version is 6022

The code is 
`   $browscap = new \BrowscapPHP\Browscap();
    $adapter = new \WurlfCache\Adapter\File([\WurflCache\Adapter\File::DIR => __DIR__.'/composer/cache']);
    $browscap->setCache($adapter);
    $browscap = $browscap-getBrowser();
    print_r($browscap);
`

**Comment by mimmi20** [comment]
What is the result?

**Comment by WhiteLoti** [comment]
stdClass Object ( [browser_name_regex] => [browser_name_pattern] => [comment] => Default Browser [browser] => Default Browser [browser_type] => unknown [browser_bits] => 0 [browser_maker] => unknown [browser_modus] => unknown [version] => 0.0 [majorver] => 0 [minorver] => 0 [platform] => unknown [platform_version] => unknown [platform_description] => unknown [platform_bits] => 0 [platform_maker] => unknown [alpha] => false [beta] => false [win16] => false [win32] => false [win64] => false [frames] => false [iframes] => false [tables] => false [cookies] => false [backgroundsounds] => false [javascript] => false [vbscript] => false [javaapplets] => false [activexcontrols] => false [ismobiledevice] => false [istablet] => false [issyndicationreader] => false [crawler] => false [isfake] => false [isanonymized] => false [ismodified] => false [cssversion] => 0 [aolversion] => 0 [device_name] => unknown [device_maker] => unknown [device_type] => unknown [device_pointing_method] => unknown [device_code_name] => unknown [device_brand_name] => unknown [renderingengine_name] => unknown [renderingengine_version] => unknown [renderingengine_description] => unknown [renderingengine_maker] => unknown )

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by mimmi20** [comment]
Did downloading the ini file and creating the cache succeed without any errors?

**Comment by WhiteLoti** [comment]
Yes compared to the other ways I've tried and received errors. Can you download and cache a file in the CLI? I downloaded it and cached it to the directory, then ran the script above and got no errors. So I knew that wurlfcache was working compared to the other times it saying that there was no active cache.

**Comment by mimmi20** [comment]
Could you try with setting the user agent as parameter to the getBrowser function?

**Comment by WhiteLoti** [comment]
Same result when setting $_SERVER['HTTP_USER_AGENT']; to the getBrowser function.

**Comment by mimmi20** [comment]
Are you trying to run your script in the CLI or in via a web server? If you are trying to run it in th CLI, you have to check, if `HTTP_USER_AGENT` key is set in the $_SERVER var.

**Comment by WhiteLoti** [comment]
I only cached with the browscap with the CLI. Running the script I used the web server.
