### ISSUE TITLE
Server error: `GET http://browscap.org/stream?q=PHP_BrowscapINI` resulted in a `503 Service Temporarily Unavailable`

### ISSUE THREAD

**Issue by amoreir** [browscap/browscap-php#208]
It looks like browscap is using Cloudflare now to avoid DDoS attacks which means it's returning html instead of returning the .ini file.
This error happens when I run **browscap:fetch** to get the config.
Any help?
Thank you.

**Comment by asgrim** [comment]
We've been using Cloudflare for a while. However since last night we have been getting unusually high volume of traffic. I've turned off the DDoS protection now though and we'll see how it goes.

But yes, the status code doesn't lie, the service was temporarily unavailable ;)

**Comment by amoreir** [comment]
Cool, thanks 👍

**Comment by rgpublic** [comment]
Hm. Seems to happen for me again. Very frustrating. And it seems I cannot specify a local file with "-r". So everything depends on this single URL. And if CloudFlare kicks in, nothing works :-(
