### ISSUE TITLE
can't download the ini-file?

### ISSUE THREAD

**Issue by swissdude** [browscap/browscap-php#209]
I'm trying to install the PHP-scripts and as stated in the docs, I try to download the browscap.ini file by issuing the command «vendor/bin/browscap-php browscap:fetch».
After a while I get an error saying the Server gave an error 522 - Origin Connection Time-out.

When I try to access the page via Browser, I get an 502 invalid Gateway error (Cloudflare).

Is this just a temporary hickup or is browscap.org down for good?

**Comment by jaydiablo** [comment]
browscap.org also doesn't load for me, @asgrim.

**Comment by asgrim** [comment]
Yeah, sorry folks, I was travelling and I got notifications we'd almost consumed all available bandwidth; I only had time to shut it down just to avoid hitting the limit. I've just got back today and turned the server back on.
