### ISSUE TITLE
incorrect display for User Agent

### ISSUE THREAD

**Issue by KyKyIIIKuH** [browscap/browscap-php#215]
Hello,
When I go to the browser "Google Chrome", UA Lookup wrote that I went to the browser chrome.
But if to come to the browser "Amigo Browser", UA Lookup wrote that I went to the browser chrome, instead of to write browser "Amigo Browser".
Also, if I log in from the browser "UC Browser", UA Lookup writes that I went with the browser chrome, instead of writing a browser "UC Browser:".
____
Когда я захожу с браузера "Google Chrome", UA Lookup пишет что я зашел с browser chrome.
Но если зайти с браузера "Amigo Browser", UA Lookup пишет что я зашел с browser chrome , вместо того чтобы написать browser "Amigo Browser".
Также если зайти с браузера "UC Browser", UA Lookup пишет что я зашел с browser chrome , вместо того чтобы написать browser "UC Browser:".
____
User Agent:
- Amigo Browser:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.197 Amigo/56.0.2924.197 MRCHROME SOC Safari/537.36

- UC Browser:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/6.1.2909.1402 Safari/537.36

- Google Chrome:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by mimmi20** [comment]
Please move this issue to the project browscap/browscap.
