### ISSUE TITLE
BrowscapUpdater::checkUpdate is inconvenient to use programatically

### ISSUE THREAD

**Issue by bertptrs** [browscap/browscap-php#216]
Currently, `BrowscapUpdater::checkUpdate` returns

- `null` when everything is fine and no action is needed
- The current version number when an update is available
- `0` in case of an error, which can either be
    1. There is no local version available
    2. There was a problem retrieving the current version number

The problem arises in the last case. If there is no local version available, then you definitely want to run the update, but when the new version number cannot be retrieved you do not want to run the update, since there might be a problem upstream.

Correct me if I'm wrong, but I've found the most convenient way to check if a local version has been cached is calling `Browscap::getBrowser()` and catching the exception, which seems a bit hackish, thus making the distinction between the two cases very hard. The difference can also be observed by reading the log, but that isn't something you want your program to do either.

I am aware that it is safe to call `BrowscapUpdater::updater` directly without checking beforehand as it checks on its own, but if you need to do some set-up before you update (locking out concurrent updates or something like that) you cannot do a quick version update, do your set-up, and then update.

I suggest changing the return value to:
- `null` when everything is fine and no action is needed
- The remote version number when an update is available, which is also returned when no local cache is available.
- (optionally) `0` if there is some issue with retrieving the version number

This way, you can write your code as follows:
```php
$updater = new BrowscapUpdater();
if ($updater->checkUpdate()) {
    // Prepare for update
    $updater->update();
    // Clean up after update
}
```

**Comment by asgrim** [comment]
Yes, I agree the multiple return types are really not ideal or intuitive. 

I think, however, if there are issues retrieving the version number then these should be thrown as exceptions, rather than having a specific return type. This would be a BC break of course, but a reasonable one. Therefore, the return values would be:

 * `null` if no new version needed
 * Version number if update is available
 * An exception is thrown if there is an issue retrieving

**Comment by bertptrs** [comment]
An exception would be even better, perhaps a `FetcherException`? That one is being used by the updater already.

**Comment by asgrim** [comment]
Yep, seems reasonable
