### ISSUE TITLE
Automatic update still works on even though it was already turned off

### ISSUE THREAD

**Issue by rogan-son** [browscap/browscap-php#225]
https://github.com/hisorange/

I set 'doAutoUpdate' to 'false' to turn off auto update.
But, it seems like still trying to update automatically.
Can you help me to disable this option?

hisorange/browser-detect/src/config/plugins.php
'doAutoUpdate' 	=> false

**Comment by mimmi20** [comment]
@rogan-son You are using `garetjax/phpbrowscap`, not this project. Please update your dependencies and try again.
