### ISSUE TITLE
How to define custom cache directory?

### ISSUE THREAD

**Issue by malaire** [browscap/browscap-php#226]
Documentation only mentions how to use custom cache directory with CLI commands, but not how to use it within PHP.

**Comment by KacerCZ** [comment]
Create instance of cache with directory you want and then call `setCache()` on `Browscap` instance:

```php
$cache = \WurflCache\Adapter\File( [ \WurflCache\Adapter\File::DIR = '/tmp/browscap-cache' ] );
$browscap = \BrowscapPHP\Browscap();
$browscap->setCache($cache);
```

**Comment by malaire** [comment]
@KacerCZ  According to documentation, those commands enable using "v2 cache directory".

I don't want to use old features, so how do I use v4 cache directory, just in different location?

Also setCache has been removed in v4.

**Comment by mimmi20** [comment]
For version 4 you have create a cache adapter yourself.

An example:
```php
$fileCache = new \Doctrine\Common\Cache\FilesystemCache($input->getOption('cache'));
$cache = new \Roave\DoctrineSimpleCache\SimpleCacheAdapter($fileCache);
$browscap = new \BrowscapPHP\Browscap($cache, $logger);
```

**Comment by mimmi20** [comment]
You may use any other cache that implements the PSR-16 (e.g. Symfony Cache).
