### ISSUE TITLE
503: Service Temporarily Unavailable. `http://browscap.org/stream?q=PHP_BrowscapINI`

### ISSUE THREAD

**Issue by reedzhao** [browscap/browscap-php#228]
I am getting error when I try to update browscap.

`wget http://browscap.org/stream?q=PHP_BrowscapINI`
```
--2017-11-27 01:03:31--  http://browscap.org/stream?q=PHP_BrowscapINI
Resolving browscap.org (browscap.org)... 104.28.16.219, 104.28.17.219, 2400:cb00:2048:1::681c:10db, ...
Connecting to browscap.org (browscap.org)|104.28.16.219|:80... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2017-11-27 01:03:32 ERROR 503: Service Temporarily Unavailable.
```

However, if I try to download through browser, the file can be downloaded.

**Comment by reedzhao** [comment]
#208

**Comment by akinor1ty** [comment]
Same here

**Comment by asgrim** [comment]
Due to extremely high levels of abuse traffic, and having almost reached our bandwidth limit for the month, I've had no option but to turn on CloudFlare's DoS protection (puts up a JS challenge). I don't have time at the moment to put measures into place to mitigate the problem, so I'm afraid you'll have to download manually in the browser for now.

**Comment by hankipanky** [comment]
Unfortunately, this is breaking our build process, which checks the version number first before attempting to download the data (if necessary).

Would it be possible for you to restrict the DDoS protection to the actual file downloads, and leave `http://browscap.org/version-number` open? All those well-behaved download clients would continue to work, and I would hope your bandwidth is not too much impacted by that.

**Comment by asgrim** [comment]
I don't believe that's possible with CloudFlare, and I'm afraid I don't have time to investigate further at the moment, sorry :/

**Comment by hankipanky** [comment]
ack thanks for responding (and sorry for addressing this here and on the mailinglist in parallel).

**Comment by asgrim** [comment]
No problem! Sorry it's not much help at the moment, but we don't get any financial support; so my main work has to take priority; it's on my todo list to make the rate limiting more effective, just please bear with me :+1: :)

**Comment by webIMT** [comment]
Hi,
we're the 1st of december, and I'm still getting an http 503 error with my cli script. Is it normal ?

**Comment by asgrim** [comment]
Hello, sorry I didn't drop everything I'm doing at the stroke of midnight to do something for free. Please be patient, I don't get paid for this.

**Comment by webIMT** [comment]
OK, thanks for you work !

**Comment by asgrim** [comment]
I have removed "I'm under attack" mode on Cloudflare now, so service should be resumed as normal. Thanks everyone, sorry about the hassle :+1:
