### ISSUE TITLE
Cloudflare blocking auto update: Bad datetime format from http://browscap.org/version

### ISSUE THREAD

**Issue by flogr** [browscap/browscap-php#230]
Since Monday, 2017-11-27, i'm getting these exceptions on my daily update of the browscap database.

On checking i recognized you seem to introduced cloudflare protection, which makes it impossible to curl for the current version.

Is this only a temporary situation or do i have to upgrade to the latest version und modify my implementation?

**Comment by asgrim** [comment]
As discussed in #228, we've enabled DDoS protection to limit bandwidth usage from abusive sources, unfortunately that means the files must be downloaded by hand at the moment, although they have not updated recently anyway.

**Comment by asgrim** [comment]
Duplicate of #228

**Comment by flogr** [comment]
Oh, thanks for the info!
