### ISSUE TITLE
Alternative method for getSourceVersion()

### ISSUE THREAD

**Issue by mostafasoufi** [browscap/browscap-php#238]
Hi Guys,

We've used this method in v2.1.1 and after upgrade to 3.1.0, this method removed.
Which method can I use instead?

Thank you.

**Comment by mimmi20** [comment]
Actually there is no alternative function. What do you want to do with this function?

**Comment by mostafasoufi** [comment]
Please see [this section](https://github.com/wp-statistics/wp-statistics/blob/2995e2b182d9f4fc15bfc78d4c9c13be557ae3d4/includes/classes/class-wp-statistics-updates.php#L228), We want to update the Browscap database if the database is available. (I'm not sure this method is correct)

Thank you.

**Comment by mimmi20** [comment]
Please use the `BrowscapUpdater` class and call the function `update`. This function will check, if a new version is available and updates the cache. You dont need to do this by yourself.

**Comment by mimmi20** [comment]
By the way, why dont you use the new version 4?

**Comment by mostafasoufi** [comment]
Thank you for providing the method. I'll be using this method.

> By the way, why dont you use the new version 4?

Unfortunately, We can't be using this version, Because many of our users use the PHP 5.6 version.
