### ISSUE TITLE
Custom directory for cache not working in v3.1.0

### ISSUE THREAD

**Issue by mostafasoufi** [browscap/browscap-php#239]
Hi Guys,

I've used the adapter to define custom directory for cache but the files stored in `vendor/browscap/browscap-php/resources`

My code:

```
use BrowscapPHP\Browscap;
use BrowscapPHP\BrowscapUpdater;
use BrowscapPHP\Helper\IniLoader;
use WurflCache\Adapter\File;

$browscap = new Browscap();
$adapter = new File(array(File::DIR => '/wp-statistics'));

try{
	$browscap->setCache($adapter);
	$browscap_updater = new BrowscapUpdater();
	$browscap_updater->update(IniLoader::PHP_INI_FULL);
} catch (Exception $e) {
	
}
```

Thank you.

**Comment by asgrim** [comment]
Please try with version 4.x series, the caching was replaced completely...

**Comment by mostafasoufi** [comment]
Unfortunately, we can't be using the v4 because our users using the PHP 5.6.

**Comment by mostafasoufi** [comment]
We using the Browscap library in our [WP-Statistics](https://wordpress.org/plugins/wp-statistics/) plugin 
 and there are many users at the moment (+400,000) and we, unfortunately, can not use version 4.

Have an idea?

**Comment by asgrim** [comment]
ah, frustrating. @mimmi20 any ideas?

**Comment by asgrim** [comment]
maybe #226 helps?

**Comment by mostafasoufi** [comment]
> maybe #226 helps?

I've seen before to open issue :))

**Comment by jaydiablo** [comment]
I believe you need to set the cache on the `BrowscapUpdater` object, not on the `Browscap` object, for the different file location to be used during the update.

```php
use BrowscapPHP\BrowscapUpdater;
use BrowscapPHP\Helper\IniLoader;
use WurflCache\Adapter\File;

$adapter = new File(array(File::DIR => '/wp-statistics'));

try{
	$browscap_updater = new BrowscapUpdater();
        $browscap_updater->setCache($adapter);
	$browscap_updater->update(IniLoader::PHP_INI_FULL);
} catch (Exception $e) {
	
}
```

Technically you don't need to instantiate the `Browscap` class in this case (I'm assuming this code just updates the browscap files), unless you're planning to do UA parsing later in the same file.

The cache adapter will need to be passed to both objects wherever they're used.

**Comment by mostafasoufi** [comment]
Doesn't work, I think there is no way to define the custom directory in this version. But we skip this issue because the upgrade to v4.0 is the only solution to fix that.

Thank you.
