### ISSUE TITLE
Allowed Memory Size in update the database

### ISSUE THREAD

**Issue by mostafasoufi** [browscap/browscap-php#240]
Recently, our users receive Allowed Memory Size error to update the database. Is there a way to restrict memory?

**Comment by mimmi20** [comment]
You could switch to not use the full file. 

If the two steps "creating the cache" and "using the cache" are placed in the same process, you should think about splitting this, but I dont know how to do this with wordpress.

**Comment by mimmi20** [comment]
@mostafasoufi Please request more information from your users. As I remember your WP-Plugin switched from browscap-php v2 to v3 not long ago. The old version should not have required less memory.

**Comment by mostafasoufi** [comment]
Yes, We switched from v2 to v3. We have a function for download Browscap and then create the cache.

It's a good solution if we splitting the processes. To confirm this job, in the below code how can do it?

```
$adapter = new File(array(File::DIR => $upload_dir['basedir'] . '/wp-statistics'));
try{
	$browscap_updater = new BrowscapUpdater();
	$browscap_updater->setCache($adapter);
	$browscap_updater->update(IniLoader::PHP_INI_FULL);

	// Update browscap last download time
	$WP_Statistics->update_option('last_browscap_dl', time());

	$message = __('Browscap database updated successfully!', 'wp-statistics');
} catch (Exception $e) {
	$message = sprintf(__('Browscap database updated failed! %s', 'wp-statistics'), $e->getMessage());
}
```

**Comment by mimmi20** [comment]
@mostafasoufi In your sample you only update the cache, but you don't do any detections.

**Comment by mostafasoufi** [comment]
We using the sample code to get browser in front-ent:

```
try {
	$browscap = new Browscap();
	$current_browser = $browscap->getBrowser();
	print_r($current_browser);
} catch ( Exception $e ) {
	print_r($e->getMessage());
}
```

But, getting the error:
```
there is no active cache available, please run the update command
```

**Comment by jaydiablo** [comment]
Just like in your update script, you'll have to specify the location of the cache:

```php
$adapter = new File(array(File::DIR => $upload_dir['basedir'] . '/wp-statistics'));
try {
	$browscap = new Browscap();
	$browscap->setCache($adapter);
	$current_browser = $browscap->getBrowser();
	print_r($current_browser);
} catch ( Exception $e ) {
	print_r($e->getMessage());
}
```

**Comment by mostafasoufi** [comment]
Thank you @jaydiablo,

Worked fine.
