### ISSUE TITLE
`check-update` command should return a sensible exit code

### ISSUE THREAD

**Issue by lode** [browscap/browscap-php#241]
Is there an automated way to test for a new version? Right no I use `browscap:check-update` but that seems to output only something human-readable:

```
[2018-01-23 12:24:31] there is no newer version available {"memory_peak_usage":"5 MB"}
```

Or:

```
[2018-01-23 12:22:11] there is no cached version available, please update from remote {"memory_peak_usage":"4 MB"}
```

It would be great to test the output of these comments from a script. Now I always execute a memory-heavy `browscap:convert` because I don't know whether it is needed.

**Comment by mimmi20** [comment]
Please use the `browscap:update` command. It checks if a new versions is availble and updates the cache if needed.

**Comment by lode** [comment]
Thanks @mimmi20!

The readme states this doesn't work on corrupted cache. Is that something that can happen regularly? And what happens if the cache gets corrupted. Does the library crash, or just don't give correct results? How would I know the cache is corrupted?

**Comment by mimmi20** [comment]
@lode The cache gets corrupted when the process breaks during cache creation e.g. because reaching the memory limit. When the cache gets corrupted you dont get correct results, but the library should not crash.

**Comment by lode** [comment]
That sounds good, thanks!
