### ISSUE TITLE
Misleading browser info due to incomplete programmatical update for PHP_INI_FULL

### ISSUE THREAD

**Issue by michalrames** [browscap/browscap-php#247]
No matter how many times I try purging and repopulating the cache, I always end up getting the following (one or more) message(s) in my app log: `cache key "browscap.iniparts.a8d" not found` (where the last triplet varies depending on which piece is missing). This is observed only with invoking BrowscapUpdater from my app, the CLI script seems to work well.

This results in a generic browser info, `..."browser":"Default Browser","browser_type":"unknown"...` instead of `...,"browser":"Chrome","browser_type":"Browser",...`

My code on PHP 7.2.5 + browscap-php 4.1 + apache2 + Ubuntu:

    ini_set('memory_limit','1024M');
    ini_set('max_execution_time', 3000);
    $bc = new \BrowscapPHP\BrowscapUpdater($this->browscap_cache, $this->logger );
    $bc->update(\BrowscapPHP\Helper\IniLoaderInterface::PHP_INI_FULL);

I tried with both filecache and memcache - same outcome. Also tried debugging the code, no error and no Exceptions are thrown.

Any suggestions towards troubleshooting or resolving this issue would be greatly appreciated

**Comment by mimmi20** [comment]
Did you get any errormessages in your log during the update?

**Comment by michalrames** [comment]
@mimmi20 I did not, I should have mentioned that in my original post. Here's the log output for update (this one is with memcached so it's fairly swift; filecache takes a few minutes to populate):

    [2018-06-02 09:29:56] slim-app.DEBUG: started fetching remote file [] {"uid":"3908611"}
    [2018-06-02 09:29:57] slim-app.DEBUG: finished fetching remote file [] {"uid":"3908611"}
    [2018-06-02 09:29:57] slim-app.INFO: start creating patterns from the ini data [] {"uid":"3908611"}
    [2018-06-02 09:30:35] slim-app.INFO: finished creating patterns from the ini data [] {"uid":"3908611"}
    [2018-06-02 09:30:35] slim-app.INFO: start creating data from the ini data [] {"uid":"3908611"}
    [2018-06-02 09:30:57] slim-app.INFO: finished creating data from the ini data [] {"uid":"3908611"}

**Comment by michalrames** [comment]
Update - looks like I'm able to populate the filecache completely using the CLI script. I am updating the issue description.

**Comment by mimmi20** [comment]
@michalrames Could you post the code snipped, where you are calling browscap?

**Comment by mimmi20** [comment]
> Also noticed the CLI script updates Full_PHP_BrowscapINI cache a lot faster than when doing so programmatically.

The Cli script checks if the cache is already built and if a new version is available.

**Comment by michalrames** [comment]
> The Cli script checks if the cache is already built and if a new version is available.

In my original post I described the scenario as purging the cache - by this I mean I manually delete all cache contents. The BrowscapUpdater as well as the CLI script get a fresh start every time. 

> Could you post the code snipped, where you are calling browscap?

Here you go, doesn't give you much more detail than in the original post.

```php
// settings.php
'cachedir' => '/var/browscap_cache',

// dependencies.php 
$container['browscap_cache'] = function ($c) {
       $cache = new \Doctrine\Common\Cache\FilesystemCache($c['settings']['cachedir']);
       return  new \Roave\DoctrineSimpleCache\SimpleCacheAdapter($cache);
};

// routes.php
$app->get('/update_browscap_def', function($request, $response, $args) {
	try {
		ini_set('memory_limit','1024M');
		ini_set('max_execution_time', 3000);
		$bc = new \BrowscapPHP\BrowscapUpdater($this->browscap_cache, $this->logger);
		$bc->update(\BrowscapPHP\Helper\IniLoaderInterface::PHP_INI_FULL);
		$body = $response->getBody();
		$body->write('done');
	} catch (Exception $e) {
		$body = $response->getBody();
		$body->write('failed\n'.json_encode($e));
	} 
});
```

**Comment by mimmi20** [comment]
@michalrames In this code you get the error?

**Comment by mimmi20** [comment]
@michalrames I looked into the code. The message you got, is a `debug` message, not an error.

**Comment by mimmi20** [comment]
@michalrames Could you also post the code snipped, where you are calling browscap for detecting and some useragents?

**Comment by michalrames** [comment]
> In this code you get the error?

No. In the actual detection (see snippet below). 

---

> I looked into the code. The message you got, is a debug message, not an error.

Yes, it is a debug message. However it is related to the malfunction of browser detection. I am able to replicate the issue by intentionally setting short PHP execution time. Then, more cache pieces are missing and I'm getting something like this:

```log
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.a71" not found [] {"uid":"ad1fc36"}
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.b30" not found [] {"uid":"ad1fc36"}
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.6e3" not found [] {"uid":"ad1fc36"}
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.dc3" not found [] {"uid":"ad1fc36"}
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.b63" not found [] {"uid":"ad1fc36"}
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.e61" not found [] {"uid":"ad1fc36"}
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.aba" not found [] {"uid":"ad1fc36"}
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.6c1" not found [] {"uid":"ad1fc36"}
[2018-05-16 23:07:46] slim-app.DEBUG: cache key "browscap.iniparts.338" not found [] {"uid":"ad1fc36"}
```
... which causes (even one single missing part) the browscap output to become this:

```JSON
{"browser_name_regex":null,"browser_name_pattern":null,"comment":"Default Browser","browser":"Default Browser","browser_type":"unknown","browser_bits":"0","browser_maker":"unknown","browser_modus":"unknown","version":"0.0","majorver":"0","minorver":"0","platform":"unknown","platform_version":"unknown","platform_description":"unknown","platform_bits":"0","platform_maker":"unknown","alpha":"false","beta":"false","win16":"false","win32":"false","win64":"false","frames":"false","iframes":"false","tables":"false","cookies":"false","backgroundsounds":"false","javascript":"false","vbscript":"false","javaapplets":"false","activexcontrols":"false","ismobiledevice":"false","istablet":"false","issyndicationreader":"false","crawler":"false","isfake":"false","isanonymized":"false","ismodified":"false","cssversion":"0","aolversion":"0","device_name":"unknown","device_maker":"unknown","device_type":"unknown","device_pointing_method":"unknown","device_code_name":"unknown","device_brand_name":"unknown","renderingengine_name":"unknown","renderingengine_version":"unknown","renderingengine_description":"unknown","renderingengine_maker":"unknown"}
```
---

> Could you also post the code snipped, where you are calling browscap for detecting and some useragents?

Here you go

```php
$app->get('/test_browscap', function($request, $response, $args) { 
	 
	$user_agent = $request->getHeaders()['HTTP_USER_AGENT'];
	if (is_array($user_agent)){
		$user_agent = $request->getHeaders()['HTTP_USER_AGENT'][0];
	} 
	try {
		$start = microtime(true);
		$browscap = new \BrowscapPHP\Browscap($this->browscap_cache, $this->logger);
		$bJson = json_encode($browscap->getBrowser());
		$elapsed = (microtime(true) - $start) * 1000;
		$response->getBody()->write('<html><body><div>Duration: '.$elapsed.'ms</div><div>User agent: '.$user_agent.'</div><div>Result: <br/>'.$bJson.'</div></body></html>');
       ....
```

**Comment by mimmi20** [comment]
Two Questions:

1. Do you use the same cache object for updating and detecting (same cache type and location)? The CLI function uses a file cache.
2. Did you forget to use the `$user_agent` variable in the `($browscap->getBrowser()` call?

**Comment by michalrames** [comment]
> Do you use the same cache object for updating and detecting (same cache type and location)? The CLI function uses a file cache. 

As far as I can tell, yes. I tested was able to replicate the issue with seemingly incomplete programmatically update separately with `\Doctrine\Common\Cache\FilesystemCache` and with `\Doctrine\Common\Cache\MemcacheCache` 

The proof that CLI update works is based on filecache, I wasn't even thinking of populating memcached with the CLI utility. 

> Did you forget to use the `$user_agent` variable in the `($browscap->getBrowser()`  call?

Nope, I'm printing the user header in the output for debug purposes and I'm leaving it to the default `getBrowser()` invocation intentionally.  That shouldn't be the issue, because it works fine when the cache is populated  correctly (i.e. no `cache key "..." not found` messages in the app log)

**Comment by mimmi20** [comment]
> I wasn't even thinking of populating memcached with the CLI utility
Thats not possible. The CLI tool uses a file cache internally, and you can't change this.

> As far as I can tell, yes
Please make sure, that you use the same cache for both processes. Otherwise you will get no results.

**Comment by mimmi20** [comment]
@michalrames Do you still have this issue?

**Comment by mimmi20** [comment]
@asgrim May we close this issue?
