### ISSUE TITLE
there is no active cache available, please use the BrowscapUpdater and run the update command

### ISSUE THREAD

**Issue by Sirgalas** [browscap/browscap-php#251]
I connect your library
do
`vendor / bin / browscap-php browscap: fetch 'redis', / var / www / site.loc / php_browscap.ini`
and
`vendor / bin / browscap-php browscap: convert`

here is the code

 ```
$ redis = new \ Redis ();
        $ redis-> connect ('localhost', 6379);
         $ cash = new \ Doctrine \ Common \ Cache \ RedisCache ();
         $ cash-> setRedis ($ redis);
        $ browscap = new \ BrowscapPHP \ Browscap (new SimpleCacheAdapter ($ cash), new NullLogger ());
        return var_dump ($ browscap-> getBrowser ());
```
getting an error

> there is no active cache available, please use the BrowscapUpdater and run the update command
> what's wrong ?

P.S. so `vendor / bin / browscap-php browscap: update` also tried the same effect

**Comment by mimmi20** [comment]
The CLI commands use a file cache.

**Comment by mimmi20** [comment]
Please call before `getBrowser`:
```
$bc = new \BrowscapPHP\BrowscapUpdater(new SimpleCacheAdapter ($ cash), new NullLogger ());
$bc->update(\BrowscapPHP\Helper\IniLoaderInterface::PHP_INI_FULL);
```

**Comment by mimmi20** [comment]
> vendor / bin / browscap-php browscap: fetch 'redis'

This creates a cache directory with the name 'redis'

**Comment by Sirgalas** [comment]
вот такой код 
```
 $cash->setRedis($redis);
        $bc = new \BrowscapPHP\BrowscapUpdater(new SimpleCacheAdapter ($cash), new NullLogger ());
        $bc->update(\BrowscapPHP\Helper\IniLoaderInterface::PHP_INI_FULL);
        $browscap = new \BrowscapPHP\Browscap(new SimpleCacheAdapter($cash), new NullLogger());
        return var_dump($browscap->getBrowser());
```
привел к такой ошибке

> Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes)

**Comment by mimmi20** [comment]
Please split this script into 2 pieces. 

1. First for updating the cache. You may need up to 500MB Ram. You should run this script once a month.
2. Second for detecting. you need less Memory.

**Comment by Sirgalas** [comment]
> You should run this script once a month.

How does cron only work through cli scripts?

**Comment by mimmi20** [comment]
You may call a php file in a cron.

**Comment by Sirgalas** [comment]
in the file should be only this code?
```
$ bc = new \ BrowscapPHP \ BrowscapUpdater (new SimpleCacheAdapter ($ cash), new NullLogger ());
$ BC-> update (\ BrowscapPHP \ Helper \ IniLoaderInterface :: PHP_INI_FULL);
```

**Comment by mimmi20** [comment]
> in the file should be only this code?

Plus the full configuration for the cache.

**Comment by Sirgalas** [comment]
By itself. Thank you. Can be closed
