### ISSUE TITLE
vendor\bin\browscap-php browscap:fetch didn't output anything

### ISSUE THREAD

**Issue by sweiguny** [browscap/browscap-php#255]
i am facing the issue, that i have no ini file fetched - at least i can't find it.
i was installing the browscap via composer:

    C:\xampp\htdocs\Test>composer require browscap/browscap-php
    Using version ^4.1 for browscap/browscap-php
    [... further composer output ...]
so i've got the last browscap version from composer...
and then ran the fetch command..
    C:\xampp\htdocs\Test>vendor\bin\browscap-php browscap:fetch

    C:\xampp\htdocs\Test>echo Exit Code is %errorlevel%
    Exit Code is 0

the fetch script did not throw an error, but it did not output anything at all. i also can't find the fetched file.

what am i doing wrong?

_Originally posted by @sweiguny in https://github.com/browscap/browscap-php/issues/210#issuecomment-441179059_

**Comment by mimmi20** [comment]
@sweiguny please run `vendor\bin\browscap-php browscap:fetch -vv` or `vendor\bin\browscap-php browscap:fetch -vvv`. If you see something in the output, please post it here.

**Comment by sweiguny** [comment]
that is the output:

    C:\xampp\htdocs\Test>vendor\bin\browscap-php browscap:fetch -vvv
    [info] started fetching remote file
    [debug] started fetching remote file
    [debug] finished fetching remote file
    [debug] started storing remote file into local file
    [debug] finished storing remote file into local file
    [info] finished fetching remote file

i've already found the ini, since i was checking the source of the command...
i found out, that the path of the ini is `vendor\browscap\browscap-php\resources`

wouldn't it be great, if the command would output that info?

**Comment by sweiguny** [comment]
Great!
