### ISSUE TITLE
Issue following system reboot (nginx)

### ISSUE THREAD

**Issue by mtstedman** [browscap/browscap-php#256]
Following any system restart I get the following error thrown on every click:

PHP Fatal error:  Uncaught Crossjoin\\Browscap\\Exception\\ParserRuntimeException: There is something wrong with the parser. The data have been re-generated without errors, but the reader still requires an update of the data... in ..../vendor/crossjoin/browscap/src/Browscap.php:183\nStack trace:\n#0 ..../vendor/crossjoin/browscap/src/Browscap.php(142): Crossjoin\\Browscap\\Browscap->update()\n#1 ...../vendor/crossjoin/browscap/src/Browscap.php(121): Crossjoin\\Browscap\\Browscap->autoUpdate()\n#2 ..../index.php(351): Crossjoin\\Browscap\\Browscap->getBrowser('Mozilla/5.0 (iP...')\n#3 {main}\n  thrown in ...../vendor/crossjoin/browscap/src/Browscap.php on line 183

**Comment by mtstedman** [comment]
Running nginx + php 7.2 (fpm)

**Comment by mimmi20** [comment]
You are not using our browscap parser. Please ask [here](https://github.com/crossjoin/Browscap) for help.
