### ISSUE TITLE
All browsers showing up as Unknown

### ISSUE THREAD

**Issue by ArianeNubee** [browscap/browscap-php#260]
I installed browscap-php 4.2 with Composer. I've updated my cache with the shell command provided. But all browsers are 'Unknown'. For example, Firefox outputs this:

```php
[
  "browser_name_regex" => "/^mozilla\/5\.0 \(.*mac os x 10.14.*\) gecko.* firefox\/68\.0.*$/"
  "browser_name_pattern" => "mozilla/5.0 (*mac os x 10?14*) gecko* firefox/68.0*"
  "parent" => "Firefox 68.0"
  "comment" => "Default Browser"
  "browser" => "Default Browser"
  "browser_type" => "unknown"
  "browser_bits" => "32"
  "browser_maker" => "unknown"
  "browser_modus" => "unknown"
  "version" => "0.0"
  "majorver" => "0"
  "minorver" => "0"
  "platform" => "macOS"
  "platform_version" => "10.14"
  "platform_description" => "macOS"
  "platform_bits" => "32"
  "platform_maker" => "Apple Inc"
  "alpha" => false
  "beta" => false
  "win16" => false
  "win32" => false
  "win64" => false
  "frames" => false
  "iframes" => false
  "tables" => false
  "cookies" => false
  "backgroundsounds" => false
  "javascript" => false
  "vbscript" => false
  "javaapplets" => false
  "activexcontrols" => false
  "ismobiledevice" => false
  "istablet" => false
  "issyndicationreader" => false
  "crawler" => false
  "isfake" => false
  "isanonymized" => false
  "ismodified" => false
  "cssversion" => "0"
  "aolversion" => "0"
  "device_name" => "Macintosh"
  "device_maker" => "Apple Inc"
  "device_type" => "unknown"
  "device_pointing_method" => "unknown"
  "device_code_name" => "Macintosh"
  "device_brand_name" => "Apple"
  "renderingengine_name" => "unknown"
  "renderingengine_version" => "unknown"
  "renderingengine_description" => "unknown"
  "renderingengine_maker" => "unknown"
]
```

Here is how I initialize Browscap:

```php
$browscap_updater = new \BrowscapPHP\BrowscapUpdater( $cache, $logger );
$browscap_updater->update( \BrowscapPHP\Helper\IniLoaderInterface::PHP_INI_FULL );

$browscap = new \BrowscapPHP\Browscap( $cache, $logger );
define( 'BROWSER', (array) $browscap->getBrowser() );
```
Am I doing something wrong?

**Comment by mimmi20** [comment]
@ArianeNubee Could you add the original useragent?

**Comment by mimmi20** [comment]
@ArianeNubee Did you get any error messages?

**Comment by ArianeNubee** [comment]
Actually, yes, I do! I was ignoring them since they disappeared after one refresh every time, but this error shows up every morning the first time I load the site:

> Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Resolving timed out after 5521 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /srv/www/dialoginsight/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185 Stack trace: #0 /srv/www/dialoginsight/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /srv/www/dialoginsight/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /srv/www/dialoginsight/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /srv/www/dialoginsight/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler in /srv/www/dialoginsight/vendor/browscap/browscap-php/src/BrowscapUpdater.php on line 312

As for the user agent, here you go :

> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by mimmi20** [comment]
Please dont do the update and the parsing in the same script. Updating the cache requires a lot of memory and time, and the browscap only updates once a month.
And if you fetches the browscap too often, you wil blocked.

**Comment by ArianeNubee** [comment]
Is that what happened here? Am I blocked?

But isn't it strange that it couldn't update even once?

**Comment by mimmi20** [comment]
Please split your script into two, one for updating and one for parsing. Then increase you your timeout, memory limit in the update script. Please test if can connect to browscap.org.

**Comment by ArianeNubee** [comment]
I split the scripts. The update script completes rather quickly.

I also tried connecting to "http://browscap.org" with in PHP with cURL and had no issues doing so. The browser is still unknown.

If it's relevant, I'm working on a [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) Vagrant machine.

**Comment by mimmi20** [comment]
Did you increse the timeout for the PHP script and curl? Do you get errors?

**Comment by ArianeNubee** [comment]
No errors. I tried increasing the execution time and memory, but it wasn't very relevant since the script takes about 1 second to load to begin with. There are no errors.

As for cURL, I'm not sure how I could do that, since the cURL call for updating, I guess, happens within your code, and curl_setopt requires a cURL handle variable. I did, however, increase it for my test call, and it didn't change the result: it works.

The following code loads in less than a second and displays:
`int(200)`

```php
<?php
	error_reporting(E_ALL);
	ini_set('display_errors', 1);

	ini_set( 'memory_limit', '1024M' );
	set_time_limit( 1000 );

	require __DIR__ . '/../../vendor/autoload.php';

	$cache_dir = dirname(  __DIR__ . '/../../vendor/browscap/browscap-php/resources' );
	$file_cache = new \Doctrine\Common\Cache\FilesystemCache( $cache_dir );
	$cache = new \Roave\DoctrineSimpleCache\SimpleCacheAdapter( $file_cache );
	$logger = new \Monolog\Logger( 'name' );

	$browscap_updater = new \BrowscapPHP\BrowscapUpdater( $cache, $logger );
	$browscap_updater->update( \BrowscapPHP\Helper\IniLoaderInterface::PHP_INI_FULL );

	$url = 'http://browscap.org';

	$ch = curl_init($url);  

	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 1000); 
	curl_setopt($ch, CURLOPT_TIMEOUT, 1000);
	curl_setopt($ch, CURLOPT_TIMEOUT, 5);  
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);  
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);  
	$data = curl_exec($ch);  
	$httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);  
	curl_close($ch);  

	var_dump($httpcode);
?>
```

**Comment by jaydiablo** [comment]
What does `$data` contain after that finishes?

**Comment by ArianeNubee** [comment]
Problem solved guys.

Somehow my cache must've gotten corrupted. I just deleted the whole cache folder and everything works now.
