### ISSUE TITLE
Dependency injection problem

### ISSUE THREAD

**Issue by vchebotarev** [browscap/browscap-php#261]
Hello. I have a task to download ini file from another url, because in case of specific download frequence my server can be banned by ip.
So the only way to use this lib and download ini from another url is to change `\BrowscapPHP\Helper\IniLoader::REMOTE_INI_URI`
But
IniLoader is beeing created in `\BrowscapPHP\BrowscapUpdater::fetch` and `\BrowscapPHP\BrowscapUpdater::update` and `\BrowscapPHP\BrowscapUpdater::checkUpdate`
So it not possible to use another IniLoaderInterface class
The only way is to decorate `\BrowscapPHP\BrowscapUpdater` and copy-paste its original methods except 1 line where IniLoader is initialized. And this is very very bad

I advice to change \BrowscapPHP\BrowscapUpdater::__construct like that
```
    public function __construct(
        BrowscapCache $cache,
        LoggerInterface $logger,
        ClientInterface $client,
        IniLoaderInterface $iniLoader,
        ConverterInterface $converter,
        Filesystem $filesystem,
        int $connectTimeout = self::DEFAULT_TIMEOUT
    ) {
        $this->cache = $cache;
        $this->logger = $logger;
        $this->client = $client;
        $this->iniLoader = $iniLoader;
        $this->converter = $converter;
        $this->fileSystem = $filesystem;
        $this->connectTimeout = $connectTimeout;
    }
```
I know it is a BC changes, but it is also possible to make parameters optional.
For examle my problem will be solved if constructor will be changed like that
```
    public function __construct(
        CacheInterface $cache,
        LoggerInterface $logger,
        ClientInterface $client = null,
        int $connectTimeout = self::DEFAULT_TIMEOUT,
        IniLoaderInterface $iniLoader = null
    ) {
        $this->cache = new BrowscapCache($cache, $logger);
        $this->logger = $logger;

        if (null === $client) {
            $client = new Client();
        }

        $this->client = $client;
        $this->connectTimeout = $connectTimeout;
        
        if (null === $iniLoader) {
            $iniLoader = new IniLoader();
        }
        $this->iniLoader = $iniLoader;
    }
```

**Comment by vchebotarev** [comment]
What do you think about it ?
I can easilly prepare PR

**Comment by asgrim** [comment]
> because in case of specific download frequence my server can be banned by ip.

The files are not updated more than once a month anyway, so you can just check for updates on a cron job to run once a week for example.

**Comment by vchebotarev** [comment]
i use docker containers, so every build goes with downloading ... 
The main point is that there are hard dependencies between classes ... see SOLID

**Comment by mimmi20** [comment]
> i use docker containers, so every build goes with downloading

You could use caches like redis, memcache outside your container.

**Comment by asgrim** [comment]
Closing as no feedback.
