### ISSUE TITLE
Allow 7.4

### ISSUE THREAD

**Issue by Fellzo** [browscap/browscap-php#265]
Need to allow installation for php 7.4

**Comment by mimmi20** [comment]
@Fellzo Please request this in our dependency project `roave/doctrine-simplecache`.

**Comment by asgrim** [comment]
Blocked by upstream issue: Roave/DoctrineSimpleCache#32

**Comment by mimmi20** [comment]
The changes in the the `roave/doctrine-simplecache` project remove the support for PHP 7.1. This is a BC.

**Comment by asgrim** [comment]
This is not a BC break, it is only a dependency upgrade. Since this is a library, when `composer update` is run, the consumer will find whichever compatible `browscap/browscap-php` and `roave/doctrine-simplecache` combination works for their PHP version.

**Comment by asgrim** [comment]
Further reading, see : https://github.com/Ocramius/PackageVersions/issues/105#issuecomment-514662205

**Comment by kanidjar** [comment]
hello @mimmi20 @asgrim, any update please? 

```roave/doctrine-simplecache``` now allows PHP 7.4.
