### ISSUE TITLE
browscap detect visitor browser as google bot

### ISSUE THREAD

**Issue by imarkdesigns** [browscap/browscap-php#284]
I would like to know if this is usual and accurate activity of the browscap. I have recent visitors who went downloading my client's brochure guide and when we check who are those visitors, it result(s) that the browser is Google Bot, and the platform is unknown. However, they provide correct email, phone number and certain info from our other questionnaires of the form. We also have anti-spam honeypot to prevent bots engaging our forms just to spam. Any idea about this?

**Comment by mimmi20** [comment]
@imarkdesigns Please add the useragent from these requests, and please explain how do you do the bot detection.

**Comment by imarkdesigns** [comment]
Currently using the browscap-php full version. using query_var of WPForms plugin I pass the variable coming from the browscap function.

```
function UAParser() {
  $agent = get_browser();
  if ( $agent->crawler ) {
    $_GET['ua'] = $_SERVER['HTTP_USER_AGENT'];
  } elseif ( $agent->ismobiledevice || $agent->istablet ) {
    $_GET['ua'] = 'Browser: ' . $agent->browser . ' / Platform: ' . $agent->platform . ' / Device Type: ' . $agent->device_name;
  } else {
    $_GET['ua'] = 'Browser: ' . $agent->browser . ' / Platform: ' . $agent->platform;
  }
}
UAParser();
```

output will be like this.

![Screen Shot 2020-01-14 at 7 10 00 AM](https://user-images.githubusercontent.com/1100419/72299820-f1568a00-369c-11ea-9feb-545ec92bdfed.png)

**Comment by mimmi20** [comment]
This is a bot from Google. If you follow the link in the useragent, you should get some information about the bot.

**Comment by mimmi20** [comment]
You should be aware of some things:
- Bots may be able to fill out forms
- The native `get_browser` function is really slow. You should use this library or an existing browscap wordpress plugin.
