### ISSUE TITLE
Instruction don't work.

### ISSUE THREAD

**Issue by joeyhub** [browscap/browscap-php#291]
```
$cache = new \Roave\DoctrineSimpleCache\SimpleCacheAdapter($doctrineFileCache); // or maybe any other PSR-16 compatible caches
$logger = new \Monolog\Logger('name'); // or maybe any other PSR-3 compatible logger

$browscap = new \BrowscapPHP\Browscap($cache, $logger);
$info = $browscap->getBrowser();
```

Where does $doctrineFileCache come from?

**Comment by asgrim** [comment]
You must provide a PSR-16 compatible cache, as per the instructions. It's up to you which you use. Not sure if we include a default usable one @mimmi20 ?

**Comment by joeyhub** [comment]
Instructions with mystery dependencies so they don't work out the box are really frustrating.

If someone has the doctrine/cache package then `new \Doctrine\Common\Cache\ArrayCache()` can be used to at least be able to straight test it (though it's a rubbish cache for production use).

I just want to see how well it performs on a cache miss though.

**Comment by joeyhub** [comment]
I'm getting more confused now because it still wants some caching.

There's this hidden away:

`$fileCache = new \Doctrine\Common\Cache\FilesystemCache($cacheDir);`

But no explanation of $cacheDir.

There are fetch and convert commands with no explanation or where they drop things or what they do.

**Comment by joeyhub** [comment]
```new \Doctrine\Common\Cache\FilesystemCache(__DIR__ . '/vendor/browscap/browscap-php/resources');```

Can there be some instruction and static method or something to get the path same as the CLI uses and then use that in the default?

Should be something like BrowsCap::getCacheDir()  which will be the ones dropped by fetch and convert or if it's able to instantiate it's own cache with cli something should be in sync with that.

**Comment by joeyhub** [comment]
For the curious... Cost of a cache miss with a malicious user agent was 3.5 seconds, much better at least than the JS implementation which takes 40 seconds or more.

**Comment by asgrim** [comment]
Thanks!

**Comment by mimmi20** [comment]
> You must provide a PSR-16 compatible cache, as per the instructions. It's up to you which you use. Not sure if we include a default usable one @mimmi20 ?

We dont implement a default cache. For the test we use the DoctineCache via a bridge.

**Comment by sanchezzzhak** [comment]
I also came across an incomprehensible example, so I'm sharing a completely ready-made example.

```php
use MatthiasMullie\Scrapbook\Psr16\SimpleCache;
use League\Flysystem\Filesystem;
use League\Flysystem\Local\LocalFilesystemAdapter;
use MatthiasMullie\Scrapbook\Adapters\Flysystem;

// ....
$dir        = __DIR__ . "/../vendor/browscap/browscap-php/resources";
$adapter    = new LocalFilesystemAdapter($dir);
$filesystem = new Filesystem($adapter);
$cache      = new SimpleCache(
    new Flysystem($filesystem)
);
$logger = new Logger('name');
$parser = new Browscap($cache, $logger);

$logger = new Logger('name');
$parser = new Browscap($cache, $logger);

$result = $parser->getBrowser($useragent);
 ```

**Comment by designosis** [comment]
> I also came across an incomprehensible example, so I'm sharing a completely ready-made example.

Wish I'd seen this three hours ago, instead of making a hundred failed guesses on the authors' intended method of implementing the simplest case usage. Vague and incomplete examples make non-brilliant people feel stupider.
