### ISSUE TITLE
Upgrade monolog-dependency to 2.x

### ISSUE THREAD

**Issue by littleant** [browscap/browscap-php#314]
Hi,

I'm unable to install another dependency with composer, because it uses monolog 2.1.
browscap currently allows monolog "^1.25.3 || ^2.0.2" which does not allow the newer monolog-version to be installed.

Can you please upgrade the dependency to monolog 2.1 so I'm able have both dependencies installed at the same time?

Thank you very much!

**Comment by mimmi20** [comment]
@littleant Why not? As long you dont try to install monolog 3, it should be possible. Couldd you add the error message from composer?

**Comment by asgrim** [comment]
`^2.0.2` allows compatibility with `2.1.*` already. It means "anything semver-compatible at 2.0.2 or above". Not sure this is `browscap/browscap-php` causing the conflict? As @mimmi20 said, posting the full composer conflict messages may help us point you in the right direction 👍

**Comment by littleant** [comment]
Sorry, I read the output wrong.
This seems to be a problem with my understanding of composer, not `browscap`.

I tried to install the [wirecard-sdk](https://github.com/wirecard/paymentSDK-php).
The SDK requires `"monolog/monolog": "^1.16"`

I can't figure out, why it doesn't resolve to `monolog/monolog 1.25.2`.
Both, `browscap` and `paymend-sdk-php` support this version.

Here's the output:

> $ composer require wirecard/payment-sdk-php
> Using version ^4.0 for wirecard/payment-sdk-php
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install wirecard/payment-sdk-php 4.0.3
>     - Conclusion: don't install wirecard/payment-sdk-php 4.0.2
>     - Conclusion: don't install wirecard/payment-sdk-php 4.0.1
>     - Conclusion: remove monolog/monolog 2.1.0
>     - Installation request for wirecard/payment-sdk-php ^4.0 -> satisfiable by wirecard/payment-sdk-php[4.0.0, 4.0.1, 4.0.2, 4.0.3].
>     - Conclusion: don't install monolog/monolog 2.1.0
>     - wirecard/payment-sdk-php 4.0.0 requires monolog/monolog ^1.16 -> satisfiable by monolog/monolog[1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.25.4].
>     - Can only install one of: monolog/monolog[1.25.2, 2.1.0].
>     - Can only install one of: monolog/monolog[1.25.3, 2.1.0].
>     - Can only install one of: monolog/monolog[1.25.4, 2.1.0].
>     - Can only install one of: monolog/monolog[1.16.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.17.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.17.1, 2.1.0].
>     - Can only install one of: monolog/monolog[1.17.2, 2.1.0].
>     - Can only install one of: monolog/monolog[1.18.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.18.1, 2.1.0].
>     - Can only install one of: monolog/monolog[1.18.2, 2.1.0].
>     - Can only install one of: monolog/monolog[1.19.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.20.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.21.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.22.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.22.1, 2.1.0].
>     - Can only install one of: monolog/monolog[1.23.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.24.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.25.0, 2.1.0].
>     - Can only install one of: monolog/monolog[1.25.1, 2.1.0].
>     - Installation request for monolog/monolog (locked at 2.1.0) -> satisfiable by monolog/monolog[2.1.0].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

I then did a "depends":

> $ composer depends monolog/monolog
> browscap/browscap-php  4.2.2  requires  monolog/monolog (^1.25.2 || ^2.0.1)

I fixed it now by doing:
* `$ composer remove browscap/browscap-php`
* `$ composer require wirecard/payment-sdk-php` which installed `monolog 1.25.4`
* `$ composer require browscap/browscap-php` which accepts the new monolog-version.

When I removed `wirecard/payment-sdk-php` composer upgraded `monolog` to `2.1.0`. So I guess the reason is, that composer does not downgrade dependencies to resolve conflicts?

Whatever the reason, sorry for your trouble!

**Comment by asgrim** [comment]
No problem at all, glad you fixed it! Dependency issues can be tricky to understand 🙂
