### ISSUE TITLE
No active cache available, please use the BrowscapUpdater and run the update command

### ISSUE THREAD

**Issue by andrei-dascalu** [browscap/browscap-php#319]
Hello,

This is more of a question, as I've follow the instructions to jumpstart my Browscap instances as such:

```php

        $adapter = new RedisAdapter($redisDriver);
        return new Browscap(new Psr16Cache($adapter), $myContainer->get(LoggerInterface::class));

```

where Redis driver is an instance of \Redis class, wrapped in Symfony Cache adapter using the Psr16 compatibility layer (but for the record, I've got the exact same issue with any cache I've tried, including Laminas or even Doctrine Array cache).

I've tried both methods to get started with the browscap.ini file (fetch + convert as well as update), so I'm not sure what the issue could be, unless I've misunderstood the way this class is meant to be created?

Thanks

**Comment by asgrim** [comment]
Hmm, not sure without more information; try checking for errors in logs, also check the contents of the cache after you do the update perhaps? Btw Doctrine Array cache doesn't persist so won't work anyway - it must be a cache that persists.

**Comment by mimmi20** [comment]
before you can use Browscap you have to build the cache with the BrowscapUpdater.

```php
$adapter = new RedisAdapter($redisDriver);
$bc = new \BrowscapPHP\BrowscapUpdater(new Psr16Cache($adapter), $myContainer->get(LoggerInterface::class));
$bc->update(\BrowscapPHP\Helper\IniLoaderInterface::PHP_INI_FULL);
```

**Comment by asgrim** [comment]
Closing as no feedback.
