### ISSUE TITLE
Add support for PHP 8 // Project still alive?

### ISSUE THREAD

**Issue by duxthefux** [browscap/browscap-php#320]
Hello,

I wanted to ask whether this project is still alive and we want to bring in support for PHP 8?

Thanks for info.

**Comment by asgrim** [comment]
Yes indeed, this project is still alive and well :) We'd be happy to take a PR to add PHP 8 support - I haven't tried it yet! :+1:

**Comment by duxthefux** [comment]
I prepared a PR (https://github.com/browscap/browscap-php/pull/321) and run it locally with PHP 8.0.0 which runs fine!

```
 htdocs/browscap-php   php8 ●  ./vendor/bin/phpunit
PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

.............................SS............................

Time: 00:00.110, Memory: 26.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 306, Assertions: 141, Skipped: 2.
```
