### ISSUE TITLE
[2.x] Invalid INI file is processed without error

### ISSUE THREAD

**Issue by KacerCZ** [browscap/browscap-php#36]
I found this problem when my IP was temporarily banned due to rate limiting at browscap.org and conent of downloaded browscap.ini was just some error message.

If conent of browscap.ini is not valid INI file, then cache.php is still created, but all internal arrays are empty.

I suggest to check count of $browsers returned from parse_ini_file() in updateCache() and if there are no records, then stop updating file.

If you find this solution valid, I can prepare pull request.

**Comment by asgrim** [comment]
@mimmi20 do we handle this better in `3.x` branch? If so, I'm going to close this.
