### ISSUE TITLE
broken php full browscap

### ISSUE THREAD

**Issue by WarHead** [browscap/browscap-php#401]
the full php browscap is broken. half of it's size.

**Comment by asgrim** [comment]
Please can you check the following? Your download may be incomplete:

```
$ tail full_php_browscap.ini 

[*]
Parent="DefaultProperties"
Comment="Default Browser"
Browser="Default Browser"
Browser_Bits="0"
Platform_Bits="0"
CssVersion=0
AolVersion=0

$ head full_php_browscap.ini 
;;; Provided courtesy of http://browscap.org/
;;; Created on Saturday, May 29, 2021 at 09:37 AM GMT+0000
;;; Keep up with the latest goings-on with the project:
;;; Follow us on Twitter <https://twitter.com/browscap>, or...
;;; Like us on Facebook <https://facebook.com/browscap>, or...
;;; Collaborate on GitHub <https://github.com/browscap>.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Browscap Version

[GJK_Browscap_Version]
$ sha256sum full_php_browscap.ini 
4621de6ab789f6d4410152a4e5a647d130ac5a53f330455a3ef597432d5b0464  full_php_browscap.ini
```

If you don't see the above, please try downloading it again.

**Comment by WarHead** [comment]
https://browscap.org/stream?q=Full_PHP_BrowsCapINI downloaded here to test manual and my script leeches always there wget -a $varlogd -v -6 -O $TARGET https://browscap.org/stream?q=Full_PHP_BrowsCapINI - both are only about 45k instead of nearly 100k.

just recognized: same links on the homepage and within my script. ;)

**Comment by asgrim** [comment]
The server is operating correctly, not sure what else to suggest here, except something your side. I simply downloaded the ini with Firefox and it is correct.

**Comment by WarHead** [comment]
did it so. strange... on my debian server it is only about 45k and even with firefox download it has only 45k... :-(

**Comment by WarHead** [comment]
hope you can get it: https://drive.google.com/file/d/1JXCPH1dvndOQifI0KM6UOZxI6oTZpHe5/view?usp=sharing that's what i get.

**Comment by asgrim** [comment]
I've cleared the Cloudflare cache, could you try again? No idea if it'll make any difference.

**Comment by WarHead** [comment]
yeah! that's it! thank you! now it is the full file size.

**Comment by asgrim** [comment]
Weird! Glad it's sorted :+1: thanks

**Comment by WarHead** [comment]
same problem again...

**Comment by asgrim** [comment]
@WarHead you shouldn't need to download it again, nothing has changed ;) please ensure you check the `/version` endpoint and only download the file when the version changes. Anyway, I purged the cache again :+1:

**Comment by WarHead** [comment]
My Debian-Server leeches every night the latest version via cronjob. The problem with the wrong length of the file is new. It never happend before my bug report. May be I should change the interval of the cronjob to monthly. 😉

**Comment by asgrim** [comment]
> My Debian-Server leeches every night the latest version via cronjob. The problem with the wrong length of the file is new. It never happend before my bug report. May be I should change the interval of the cronjob to monthly. 😉

You should only download the ini file if the version endpoint changes 😉

**Comment by WarHead** [comment]
yeah, may be. but therefore I had to write a parser for the browscap homepage and I've no desire to do so. ;) I'm a lazy old man. ;)

**Comment by asgrim** [comment]
What language are you using? There's plenty of existing options already which handle this?

**Comment by WarHead** [comment]
i would do it simple as linux script. where could i get ready ones?

**Comment by asgrim** [comment]
Check out https://github.com/browscap/browscap/wiki/Using-Browscap for a few implementations, typically people use one of these if they're using a language

**Comment by WarHead** [comment]
great, thx!
