### ISSUE TITLE
Excuse me, do you have parameter parsing??

### ISSUE THREAD

**Issue by scottwang0611** [browscap/browscap-php#618]
I would like to know the meaning and possible values of each field.

{
    "result": 111,
    "message": "111",
    "datas": {
        "browser_name_regex": "/^mozilla\/5\\.0 \\(.*linux.*android.10;.*\\) applewebkit.* \\(.*khtml.*like.*gecko.*\\) chrome\/.* mobile safari\/.* edga\/108\\..*$/",
        "browser_name_pattern": "mozilla/5.0 (*linux*android?10;*) applewebkit* (*khtml*like*gecko*) chrome/* mobile safari/* edga/108.*",
        "parent": "Edge 108.0 for Android",
        "comment": "Edge 108.0",
        "browser": "Edge",
        "browser_type": "Browser",
        "browser_bits": "32",
        "browser_maker": "Microsoft Corporation",
        "browser_modus": "unknown",
        "version": "108.0",
        "majorver": "108",
        "minorver": "0",
        "platform": "Android",
        "platform_version": "10.0",
        "platform_description": "Android OS",
        "platform_bits": "32",
        "platform_maker": "Google Inc",
        "alpha": false,
        "beta": false,
        "win16": false,
        "win32": false,
        "win64": false,
        "frames": true,
        "iframes": true,
        "tables": true,
        "cookies": true,
        "backgroundsounds": false,
        "javascript": true,
        "vbscript": false,
        "javaapplets": false,
        "activexcontrols": false,
        "ismobiledevice": true,
        "istablet": false,
        "issyndicationreader": false,
        "crawler": false,
        "isfake": false,
        "isanonymized": false,
        "ismodified": false,
        "cssversion": "3",
        "aolversion": "0",
        "device_name": "general Mobile Phone",
        "device_maker": "unknown",
        "device_type": "Mobile Phone",
        "device_pointing_method": "touchscreen",
        "device_code_name": "general Mobile Phone",
        "device_brand_name": "unknown",
        "renderingengine_name": "Blink",
        "renderingengine_version": "unknown",
        "renderingengine_description": "a WebKit Fork by Google",
        "renderingengine_maker": "Google Inc"
    }
}

**Comment by mimmi20** [comment]
@scottwang0611 Please ask in the future in the https://github.com/browscap/browscap project about the properties, as this is the place where they are defined. You may find the information in the wiki there: https://github.com/browscap/browscap/wiki/Resource:-User-Agents-Database#properties-reference.
