### ISSUE TITLE
get fatal error

### ISSUE THREAD

**Issue by hamburger123456** [browscap/browscap-php#71]
My site will get sometimes this error:
<br />
<b>Fatal error</b>:  Uncaught exception 'phpbrowscap\Exception' with message 'temporary file already exists' in /www/htdocs/abc/123/scripts/Browscap.php:517
Stack trace:
#0 /www/htdocs/abc/123/scripts/Browscap.php(289): phpbrowscap\Browscap-&gt;updateCache()
#1 /www/htdocs/abc/123/collect.php(112): phpbrowscap\Browscap-&gt;getBrowser(NULL, true)
#2 /www/htdocs/abc/123/collect.php(39): pageview()
#3 {main}
  thrown in <b>/www/htdocs/abc/123/scripts/Browscap.php</b> on line <b>517</b><br />

in my PHP-file I have the following:
<?php
       use phpbrowscap\Browscap;
        //Browscap
        ini_set('memory_limit', '265M');
        require 'scripts/Browscap.php';
       // Create a new Browscap object (loads or creates the cache)
        $bc = new Browscap('/www/htdocs/abc/123/cache');
        $bc->lowercase = true;
        $current_browser = $bc->getBrowser(null,true); 

I think is happens when the file is called by different user in a short period.
What can I do?

**Comment by mimmi20** [comment]
You could run this in a separate process. You may have to remove the cache.lock file in your cache directory.

```
$browscap = new phpbrowscap\Browscap($cacheDir);
$browscap->updateCache();
```

After this you should add the line 

`$bc->doAutoUpdate = false;`

to your script.


Please look at #20 for additional information.
