### ISSUE TITLE
Something not right, memory leak?

### ISSUE THREAD

**Issue by kendrik** [browscap/browscap-php#76]
I get this error:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2329600 bytes) in path-to-Browscap.php on line 505 

Line 505 is this: $browsers = parse_ini_file($ini_path, true, INI_SCANNER_RAW);

I have the latest version of browscap.ini

When using the old browscap.php (v1.0) file it works fine, tried using v2.0 from here on github but get errors, cannot get this version of the files to work. I have diff them, there are a fair few changes but not sure about what the problem is and why just these changes in the file are stopping it from working.

**Comment by jorisrietveld** [comment]
Same problem here.

**Comment by asgrim** [comment]
Browscap requires a much  higher memory limit to operate, please see issue #20 for suggestions :) thanks!

**Comment by mimmi20** [comment]
Please look into Issue #72.
