### ISSUE TITLE
Retag 2.0.3 with dcfe807ed98501f0cb2d15c6622ab9d7ab260f3c

### ISSUE THREAD

**Issue by bglover** [browscap/browscap-php#77]
The tag was created before [pull request 44](https://github.com/browscap/browscap-php/pull/44) was merged. As such, the tag incorrectly reports versions 2.0b instead of 2.0.3. Caches are built by version number, therefore composer installs are all dependent on 2.0b.

I propose a new tag for 2.0.3 and a tag for 2.0b using 50336e6.

**Comment by asgrim** [comment]
Does Composer get funny about moving tags around?

Also, why not just use 2.0.4? :smile:

**Comment by bglover** [comment]
If you have packagist setup to automatically pull changes from your repo then it's fine.
