### ISSUE TITLE
Temporary file already exists.

### ISSUE THREAD

**Issue by BondITSolutions** [browscap/browscap-php#79]
I've required browscap using composer as follows:

    "require": {
      "browscap/browscap-php": ">=1.0"
    }

I've created the caching directory in `vendor/browscap/browscap-php/cache`. Next, in my code I use the following code:

    $browscap = new phpbrowscap\Browscap('vendor/browscap/browscap-php/cache);
    $info = $browscap->getBrowser();

And I get the error 'temporary file already exists'. The files: `browscap.ini` and `cache.lock` in the directory `vendor/browscap/browscap-php/cache` are created however. I've tried the suggestion of adding `$browscap->doAutoUpdate = false;` right after creating the browscap object, but this didn't change a thing. I've also toyed around with the `cache` directory rights, removing `cache.lock`, but leaving the `browscap.ini` file, and unabling it to write `cache.lock`: this didn't do a thing either. 

What am I doing wrong in my two lines of PHP code to get this to work..?

**Comment by emkookmer** [comment]
Why do you want to put a "data" file in your vendor directory?

I would put it in the ``/tmp`` directory

**Comment by BondITSolutions** [comment]
I figured that if it wanted to cache something, I'll let it write to a cache directory in its own directory. Will putting it in the `/tmp` directory fix my problem?

**Comment by emkookmer** [comment]
If you're running your site/application on a linux machine, then yes it should resolve your problem

**Comment by mimmi20** [comment]
@BondITSolutions It should not matter what kind of OS you are using, or where your cache is located.

Creating the Cache needs some time. If the creation of the Cache is not finished when a second Request is started you will get this error.

You also should look into your Logs and you should control if the download of the Browscap.ini was successful to make sure there are no other errors.

Before using Browscap within your project, please call ```$browscap->updateCache();``` in an separate process, may be in a Cronjob.
Then in your project you have to disable the AutoUpdate.
