### ISSUE TITLE
Investigate failing builds on OSX

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-php#96]
I have disabled OSX builds on travis as it is failing. 

Investigate why, and if we don't need to build on OSX, we won't. I don't think it's critical.

**Comment by jaydiablo** [comment]
I encountered the same on my fork.  I pinged the Travis team on twitter and they said that they removed the restriction on multi-os builds, so now all repos are building OSX if it's defined in the travis.yml, however, PHP support isn't available yet:

https://github.com/travis-ci/travis-ci/issues/2313

https://twitter.com/travisci/status/638772380064718849

**Comment by asgrim** [comment]
Ahh, thanks for info & linking to the issue :)

**Comment by asgrim** [comment]
@mimmi20 OSX builds are disabled currently, can you make a PR to test if that's the case please?

**Comment by mimmi20** [comment]
@asgrim How do we test this? We actually dont test on OSX.

**Comment by asgrim** [comment]
Enable the platform on Travis ;)

**Comment by mimmi20** [comment]
The ticket travis-ci/travis-ci#2313 jaydiablo mentioned earlier is still open.
