### ISSUE TITLE
Travis builds receive Too Many Requests errors

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap-php#99]
This is related to browscap/browscap-site#19.

**Comment by asgrim** [comment]
@mimmi20 also note that I have a potential solution (still need to implement it) that should overcome the rate limiting

**Comment by asgrim** [comment]
I have resolved this - I have taken advantage of Travis-CI's caching ability to cache the file. I will simply clear the cache each time a new release of `browscap.ini` is made, or as some cherry-on-top, we can add the version checking to the [.travis-scripts/cache-browscap.sh](https://github.com/browscap/browscap-php/blob/master/.travis-scripts/cache-browscap.sh) script
